### ISSUE TITLE
Environment variables set by MSI installation not always available after install

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#104]
Hello,

We have found a critical bug in PSAppDeployToolkit.
Affected Versions of PSAppDeployToolkit: 3.6.7 and previous
Tests were made on: Windows 7 x64 Enterprise
Tested on two machines (domain productio

![testenv zip](https://cloud.githubusercontent.com/assets/13620987/10604481/3ea36758-772d-11e5-94ab-e55adac9044e.png)

n machine, and non-domain clean test machine)

We have discovered this issue, when wrapped one particular MSI package with PSAppDeployToolkit.
The MSI has system environment variable, which is needed for application to work.
When we installed original MSI with psexec, then application worked fine.
When we installed the same MSI wrapped with PSAppDeployToolkit with PSExec, then by running application it shows us error "missing environement variable". But when we check in My Computer->Properties->Change->Advanced->Environment Variable->System variables it is present there. After re-logon to windows application being to work.

Then I decided to check if this is really issue of PSAppDeployToolkit.
I have created a new MSI project in installshield with only one feature and component.
I added a file "WodrPad.exe" (taken from Windows folder) and set it to be installed to [INSTALLDIR] -> "C:\Program Files (x86)\TestEnv\"
Then I added in project new system environment variable "TestEnv" which value is [INSTALLDIR]
So if I install this new "TestEnv 1.0.0.msi" with psexec, I can open new CMD.exe shell and run "%TestEnv%WordPad.exe" and it opens WordPad. But if I install this new "TestEnv 1.0.0.msi" with with PSAppDeployToolkit with psexec, I open new CMD window and "%TestEnv%WordPad.exe" doesn't work. I write "SET | FINDSTR TestEnv" and it doesn't find this variable. But if I open "My Computer->Properties->Change->Advanced->Environment Variable->System variables" it is present there.
In my opinion PSAppDeployToolkit must not influence regular installation process, the expected behavior is like pure MSI with pexec works -> system environment variable is working without re-logon to windows.

I attach project file which can be used for tests.
Rename attached file extension from .png to .zip
There is InstallShield MSI project, and configured PSAppDeployToolkit to install TestEnv 1.0.0.msi
Please let me know if any additional info needed.

**Comment by mmashwani** [comment]
The toolkit doesn't do anything out of the ordinary with environment variables. When you open a process, that process loads all of the environment variables currently loaded on the system into it's environment block. If that process or any other process creates a new environment variable, it is not recognized unless you make a Windows API call to refresh the environment block for explorer.exe. From then on, any new process that you open will recognize the new environment variables.

Function "Refresh-Desktop" in the toolkit will refresh the environment variable block for Explorer so that any new processes recognize the newly created environment variable. Function "Refresh-SessionEnvironmentVariables" will reload all of the environment variables from the registry for the current process so that it too can use any newly created environment variables.

**Comment by AcidUser85** [comment]
but why it doesn't work only when using toolkit?
pure MSI installed under system account environment variables get updated properly.
if Toolkit operation prevents these variables from update then it is undesired behavior
Since this occurs only when using toolkit, maybe it is reasonable to mandatory update them?
Seems like toolkit operation with env. variables hijacks them from regular update when you simply install MSI.

**Comment by mmashwani** [comment]
What exactly doesn't work when using the toolkit?
I'm not sure what you mean by pure MSI installed environment variables gets updated properly. How are you verifying this? What is your test for what is or is not proper?

The toolkit does not hijack anything the system or the MSI does by default. The method that Windows processes use to update the environment block and keep it updated is kind of complicated and when deploying software that modifies environment variables, you have to make sure you understand how this process works to know how to troubleshoot any issue you encounter.

Whatever the issue is that you're encountering, I really don't think it has to do with the toolkit. The process that the toolkit is running in will not recognize the environment variable created by the MSI because the MSI was created by another process. Also, a process can only update it's environment block when it is started. Since the toolkit process launched the MSI, it cannot load or recognize environment variables created by the MSI. Only new process opened by the toolkit will recognize the new environment variables. That is why we have the function Refresh-SessionEnvironmentVariables. It lets you load environment variables from the registry so that the current process can see new environment variables.

**Comment by AcidUser85** [comment]
You misunderstood the problem. I dont need to access env.variables in the script or during script execution. The problem is that installed by MSI package env.variable does not work, if this MSI was installed by the toolkit. By does not work I mean AFTER package is istalled, when you run the application from shortcut, application does not see this env.variable until re-logon is performed. This does not occur if MSI is istalled without toolkit.

**Comment by AcidUser85** [comment]
And this means problem is because of toolkit. I have understanding of deployment scripts and env.variables of uset,system and process type and I have built own advanced wrappers on vbscipt.

**Comment by mmashwani** [comment]
OK, I understand what your problem is, but it's still not something caused by the toolkit. The toolkit simply executes the MSI, it does not interfere with anything the MSI does.

It seems like the MSI makes the environment variable change, but it does not refresh the Explorer environment block so that new processes recognize the environment variable. That is why it only works after you log off and log back onto the machine.

It seems like you're testing the MSI in two different ways.
1) Execute the MSI using psexec. Are you executing the MSI in the SYSTEM context when you do this?
2) You are executing the MSI by using the toolkit as a wrapper. I don't know how you are executing the wrapper. Are you using psexec? Are you using SCCM or some other deployment tool? Are you executing in the SYSTEM context? If you execute the MSI using this method and you do not use the toolkit as a wrapper, do you get the same behavior?

**Comment by AcidUser85** [comment]
Both times I use psexec and install locally.
Commands:
1) psexec.exe -si msiexec.exe /i "C:\Path\To\TestEnv 1.0.0.msi" /qn
- after install no issues with system-env.variable. works without re-logon.
2) psexec.exe -si "C:\Path\To\Deploy-Application.exe"
- after install system-env.variable doesn't work until re-logon is performed.

So, tests are made in same conditions. Doesn't work if was installed with wrapper toolkit.

**Comment by AcidUser85** [comment]
My colleague spent couple of days wondering why original application does not work after adding wrapper toolkit. When he said that env variable installed by MSI does not work if MSI is installed by wrapper, I did not beleave him until tested myself.

**Comment by mmashwani** [comment]
I just downloaded the MSI you attached and ran a couple of tests. I was not able to confirm any of the results you report.

1) I executed the MSI by itself from an elevated PowerShell command prompt. I did not use psexec.exe to launch the install. After the install, I checked ```HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment``` to see if the new environment variable had been created and saw that it was there. I then opened up a NEW PowerShell process and typed $env:TestEnv and saw that the process did not recognize the environment variable.

2) I uninstalled the MSI. I confirmed that the environment variable was deleted by the uninstall from the registry key: ```HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment```. I executed the MSI using psexec.exe. I used the same command you shared above. I once again check the registry and saw that the environment variable was created. I opened a NEW PowerShell process and saw that the process did not recognize the environment variable when I typed in $env:TestEnv.

If I logged off and logged back onto the machine, the environment variable was recognized.

If I went to "My Computer->Properties->Change->Advanced->Environment Variable->System variables", the environment variable was recognized without having to log off and log back into the machine. However, checking for the environment variable this way invalidates the test. When you check for the existence of an environment variable this way, Windows makes an API call to update the Explorer environment block when you press the OK button to get out of the system properties menu. I suspect you were probably verifying the existence of your environment variable using this method and thus causing the Explorer environment block to be updated. This makes sense, because MSIs do not update the Explorer environment block by default. You would have to create a custom action to do so. Or, if you're using the toolkit, call the Refresh-Desktop function after installing the MSI to update the environment block.

**Comment by AcidUser85** [comment]
I used after install I opened new CMD window (not powershell) and run commad: SET | FINDSTR TestEnv
Installing with psexec under system account in interactove mode and worked just after install. Installing with psexec+toolkit, then opened cmd and run that command - this did not work. Try the same method. This MSI was created for demonstration. We try to avoid unnecessary reboots and re-logons, if this works with psexec+msi, then, logically this should work the same with psexec+toolkit

**Comment by mmashwani** [comment]
I just installed the MSI by itself from an elevated command prompt. I did not use psexec. Then I opened up a new CMD window and tried the ```SET | FINDSTR | TestEnv``` command and it did not find the TestEnv environment variable.

Let's keep psexec and the toolkit out of our tests. If I can't get this to work by just installing the MSI by itself, then psexec and the toolkit do not matter.

And that makes sense to me because a default MSI has never, from version 1.0 to 5.0, updated the Explorer environment block. I have always had to create a custom action to make the appropriate Windows API call to make Windows recognize newly created environment variables without having to log off and lock back on. We created the Refresh-Desktop function because MSIs do not have this ability by default.

**Comment by AcidUser85** [comment]
For me it always worked without custom actions. This is because of interactive mode. I never used custom actions for that and env.variables in MSI table always worked for me when installing pure MSI or by vbscript wrapper

**Comment by mmashwani** [comment]
Interactive mode should not affect that behavior at all. I don't know what to say other than that it does not work that way for me and never has unless I made a special Windows API call. I just ran several tests with the MSI you provided and was not able to get Windows to recognize the environment variable without logging of and then back on. I would suggest you run your test on a clean machine or make sure the environment variable is deleted before running your test. Also, don't check the environment variable from System Properties as that will invalidate the test because that dialog windows make the Windows API call when you press OK.

**Comment by AcidUser85** [comment]
I do not agree that psexec should be ommited. Psexec is the only true pre-deployment test that works in 99% cases

**Comment by AcidUser85** [comment]
Should I record a video to demonstrate this? I never messed with custom actions to make env variables work, those always worked out of stock :)

**Comment by mmashwani** [comment]
Sure, make a video. What you're telling me goes against default MSI behavior and I can't verify in my independent tests. Also, there is no need to involve psexec in our tests. Show me that a regular MSI behaves the way you say it does when you install it by just using msiexec.exe. Adding psexec is just another unnecessary step in the process that adds complexity. Make sure the environment variable does not already exist in the registry. Show a shot of the registry key so we know what is and isn't there already before the MSI install.

**Comment by AcidUser85** [comment]
No need registry key.
I demonstrate windows "Env Variable Settings" GUI dialog, where it is visible that each time package installed env.variable gets added and when package uninstalled it gets removed.
I just spotted in your previous comment "Then I opened up a new CMD window and tried the SET | FINDSTR | TestEnv"
You have a typo there. The correct command is: "SET | FINDSTR TestEnv", only one time "|" sign.
Here is a recorded video demonstrating toolkit issue: https://www.youtube.com/watch?v=QCG15KlFtoc&feature=youtu.be

**Comment by That-Annoying-Guy** [comment]
Dear AcidUser85, I saw the video. 
Why didn't you use a new CMD window after installing your test.MSI? I've never seen a CMD window acquire new environment vars after it's been spawned.

Regardless, it would be interesting to if calling Refresh-Desktop after you install the MSI would fix your situation. Old or new CMD window.

**Comment by AcidUser85** [comment]
Hi That-Annoying-Guy,
Because it doesn't matter. We found this bug in different situation and when application failed from startmenu shortcut. That application did not see environment variable installed by msi and only in case if this msi was installed using toolkit.
I know how this thing in Windows works. Envrionment variable does not update for the current "already opened" CMD window. That's why I open new CMD window, which gets updated environment variables. You can see on video, after opening new CMD window, if I install pure MSI, then env.variable is visible. If installed with toolkit, then no. The video clearly demonstrates this.

**Comment by mmashwani** [comment]
I just tried the same test as you on a Windows 8 machine and was not able to replicate what you showed in the video. The main reason being that I do not open up the system properties menu to check for the existence of the environment variable. There is a reason I asked you not to check for the environment variable from that menu and to instead check it from the registry. If you open the system properties menu to check for existence of the environment variable, that menu makes a Windows API call to refresh the Explorer environment block. That invalidates your test.

If you can show the same behavior but instead check for the existence of the environment variable from the registry instead and do not open the Systems properties menu at all, then we have something.

**Comment by AcidUser85** [comment]
mmashwani, OK, then how can you explain that when I did:
1) install MSI with Toolkit
2) Opened system properties menu to check for the existence of the environment variable
3) Opened new CMD window and observed that env.variable not visible
If as you say it calls "Windows API" to refresh the Explorer environment block, then why env variable did not show up this time?
Logically it should be visible in both tests, even if opening system properties menu invalidates the test.
So it means there is no connection with Windows API call, otherwise test results would be the same.
Okay, I can repeat same tests with registry and I give 100% results will be the same.

**Comment by mmashwani** [comment]
I can't explain something I can't reproduce on my end. First step is to make sure we're doing the test in the same manner. If I we can both reproduce the behavior then I have something I can fix. Let me know when you re-run the test.

**Comment by AcidUser85** [comment]
Hi,
I have recorded second video: https://www.youtube.com/watch?v=6IqRfw-Oxe8&feature=youtu.be
It shows that env.variable actually is added to HKLM registry.
BUT! this proves that PSAppDeployToolkit influences on installation process, because MSI does not behave is it originally does. MSI installation properly updates shell object with new environment variable. In case if MSI is installed by toolkit - this does not happen as it normally should.

**Comment by AcidUser85** [comment]
after adding "Refresh-Desktop" it worked, Toolkit then properly updated shell object and environment variable after that were visible in new CMD shell window.
and this means - that "Refresh-Desktop" must be included in script by default, because only with this function PSAppDeployToolkit behaves as original MSI

**Comment by amotaz** [comment]
There is something else going on here, some other factor affecting the results. I've done my own testing and I'm getting different results from both you and mmashwani. We're going to investigate this further.

**Comment by AcidUser85** [comment]
This happened on two clean hyperV windows 7 test machines and also on hyperV windows 7 production machine.
By the way looks like that previous bug with not detected MSI now is fixed since version 3.6.6. Since we updated script we no longer see this problem

**Comment by AcidUser85** [comment]
HyperV test machines only have .Net 4.0 installed and are not updated with latest microsoft patches. We use them for repackaging and early tests. On the other side production machine has all latest patches installed, hence this is not related to OS.

**Comment by mmashwani** [comment]
There is no bug in the toolkit that causes this issue. All the toolkit does is execute the MSI. It behaves differently for me on Windows 8.1 as I can't replicate your results. A colleague that ran the tests on Windows 7 machines was able to get the environment variables to update when he installed using regular MSI or when using the toolkit.

Various Google searches show that this MSI feature behaves pretty inconsistently for people across Windows environments. For some people, it works just fine. For some people, if they open CMD as unelevated, then it does not work. For some people, if there is a pending reboot, then the MSI does not successfully update environment variables for the system.

If you need to update environment variables consistently, then I suggest you call the refresh function in your script after installing the MSI.

Just some of the google links on the topic:
https://github.com/nodejs/node/issues/603
http://serverfault.com/questions/8855/how-do-you-add-a-windows-environment-variable-without-rebooting
http://stackoverflow.com/questions/40311/installer-changes-path-variable-changes-dont-show-up-in-command-shell
http://serverfault.com/questions/8855/how-do-you-add-a-windows-environment-variable-without-rebooting
http://stackoverflow.com/questions/6979741/setting-environment-variables-requires-reboot-on-64-bit

**Comment by AcidUser85** [comment]
I cant imagine the case when someone would open CMD unelevated. The toolkit purpose is too wrap package for deployment. That means that SCCM will be used. That means it will be installed with system account. And that means that the process always will be maximum elevated.

**Comment by amotaz** [comment]
Since the results are inconsistent, we're going to test out adding a refresh-environment command to the end of the install msi function (as you suggested) in order to make it more consistent.  If adding this doesn't cause some other instability, we'll add it in a future version.

**Comment by mmashwani** [comment]
Different security contexts behave differently. Even system doesn't always have full access to do all things. Different GPOs and security baselines in different environments will affect how things interact with each other. I have no idea with is causing different results for three of us on this thread and thousands of others on various threads on the internet in regards to this issue.

**Comment by AcidUser85** [comment]
But this is not only msi related. Todays same issue that my colleague faced with, he used setup.exe and answer file. So I guess for clean tests "SETX -m" shell command could be used

**Comment by AcidUser85** [comment]
Test machines are not connected to domain and not managed with GPO

**Comment by mmashwani** [comment]
What ever the reason for why people see different results, we do have a solution. Use the refresh function from the toolkit.

**Comment by AcidUser85** [comment]
I already understand that I will have to add this function manually at the end of installation for all deployments. I just wanted to demonstrate that this issue happens for us. If this can be fixed - great, if not, then someone, who has the same issue, will be able to find this thread and will find the answer.

**Comment by AcidUser85** [comment]
Still unclear why exactly with the toolkit this problem occurs :) by taking into account that test were made on the same machine, in the same admin elevated CMD, UAC enabled, GPO policies not enabled. Both tests were made in same conditions. The only difference was - installing pure msi or installing this msi using toolkit.

**Comment by amotaz** [comment]
We added a refresh-desktop command to the execute-msi function to address this.

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/aced05675ebf8461df4371a1b0b5e0f8a9942289

**Comment by cyborgrd** [comment]
Hello. I have similar problems with MindManager 16. When i install the MSI directly, it works fine. If i try to install within the wrapper via Execute-MSI or Execute-Process the Software not working. There seems to be some problems with Custom Actions where register many DLL's. I cannot find out, what the problem is. The problem appears only if the MSI installed within the wrapper. Is absolutelly not matter who trigger the Wrapper (System Acc or Admin Acc). I tried manually triggering with the Deploy-Application.exe ot Deploy-Application.ps1, tried to install with SCCM, always got the same problem.
