### ISSUE TITLE
[Bug] Variable $envTemp has a "\" at end

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#1055]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2

### Describe the bug

For better using of the Variable $envTemp, it would be better to remove last backslash from path

### Steps to reproduce

type $envTemp will see the patch with "\"

Better to use:

`[String]$envTemp = [IO.Path]::GetTempPath().TrimEnd('\')`

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile
```

**Comment by cyborgrd** [comment]
Solution: 

[String]$envTemp = [IO.Path]::GetTempPath().TrimEnd('\')

**Comment by LFM8787** [comment]
I think the better use of any path is to use the specific Cmdlets for this called [Join-Path](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path), it can handle different situations...

**Comment by mjr4077au** [comment]
The slash has been there since forever and even if you're concatenating your own strings, `C:\Windows\Temp\\tempfile.exe`, with the extra slash, is still a valid path for any PowerShell cmdlet.

Agreed with LFM, the PowerShell utilities like `Join-Path` and `[System.IO.Path]::Combine()` exist for a reason, and paths with bad endings can exist anywhere at any time.

Because someone could be relying on the trailing slash being there, and because it causes no harm, we won't be trimming it off.
