### ISSUE TITLE
Fix the misuage of the [switch] type variables all along the AppDeployToolkitmain.ps1 code

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#1062]
### Summary of the new feature / enhancement

In a function call, if `-switch` is provided, `$switch.isPresent` will be true, it will be false otherwise. So : 

- Testing the value of a switch should use the `.isPresent`
- No need to initialize a` [switch]$myparam = $false` because it's the default value.
- Initializing `[switch]$myparam = $true` is a misusage : if you want $myparam to be $true, pass -myparam to the function call.

See https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoiddefaultvalueswitchparameter?view=ps-modules for best practice with the [switch] type.

**Comment by DanGough** [comment]
This has already been addressed in the v4 codebase which will be hitting public preview later this year.

**Comment by mjr4077au** [comment]
Just to extend on this also, testing of a switch's true/false state does not require testing its `.IsPresent` member explicitly. This is more annoying to read, and doesn't truly signify whether the switch is present or not, just whether its true or false. Testing of a switch's presence irrespective of its value can only be reliably performed via checking the `$PSBoundParameters` dictionary.

Regarding why testing of the `.IsPresent` member isn't necessary, is because PowerShell will implicitly call the switch's `ToBool()` method when testing it for its true/false state. This can be verified by reviewing PowerShell's source code: https://github.com/PowerShell/PowerShell/blob/4f7819d143869b79bdaa559490d2de7553b50010/src/System.Management.Automation/engine/LanguagePrimitives.cs#L1008-L1009

All poor usages of switches within our codebase have been addressed like Dan has said, however there's no explicit testing of a switch's `.IsPresent` member, nor will there be for the reasons stated above.
