### ISSUE TITLE
[Feature] Option to deactivate minimize windows

### ISSUE THREAD

**Issue by Hardexit** [PSAppDeployToolkit/PSAppDeployToolkit#1104]
### Summary of the new feature / enhancement

I can't find an option in v4 that prevents minimizing all active applications, if I unleash this on users I get stoned. Am I just overlooking the option or is it really missing?

**Comment by mjr4077au** [comment]
On the call to Show-ADTInstallationWelcome, you can add `-NoMinimizeWindows` to achieve what you're after.

**Comment by Hardexit** [comment]
Ok, then I'll have to do it inline, thought it would be good as a global variable in the new config file.

**Comment by mjr4077au** [comment]
I can understand the desire for that, but there's an inconsistency between `Show-ADTInstallationWelcome` and `Show-ADTInstallationPrompt` where the former minimizes by default and the latter does not. As such, retrofitting a config option here won't be possible and it was important for v4 to maintain existing defaults to provide expected behaviour to users and ease the migration process.
