### ISSUE TITLE
[Bug] PSADT environment variables missing after module import

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#1119]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

I'm wondering how can I initialize the PSADT environment variables located in [New-ADTEnvironmentTable.ps1](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/main/src/PSAppDeployToolkit/Private/New-ADTEnvironmentTable.ps1).

I've tried _Import-Module PSAppDeployToolkit_ and _Initialize-ADTModule_ without success. What am I missing here?

I would initialize all PSADT variables in my custom PSADTv3 module for ease of management.

Thanks!

### Steps to reproduce

1. Install-Module PSAppDeployToolkit
2. Import-Module PSAppDeployToolkit
3. Initialize-ADTModule
4. Get-Variable

For instance, all variables starting with $env are missing.

### Environment data

```console
Windows 11 24H2
Windows Powershell 5.1
Powershell 7.4.6
```

**Comment by mjr4077au** [comment]
They're only available after the call to `Open-ADTSession` so that a user's console session doesn't get contaminated when using functions that require the module be initialised but don't require a session.

**Comment by DanGough** [comment]
V4 docs page for variables will be going up on the site later today that will explain this.

**Comment by mjr4077au** [comment]
I've added `Export-ADTEnvironmentTableToSessionState` into our develop branch via https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/1a40b62e09a011f187821275cb52e8776dbe6496, it'll be available for usage with PSAppDeployToolkit 4.1.0 when it's released.

When this [GitHub Action](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/12246582178) finishes, you'll be able to download a pre-release artifact and confirm this works to your expectation. If testing from the command line, you can call `Export-ADTEnvironmentTableToSessionState -SessionState $ExecutionContext.SessionState` to test, or within functions to keep the exports local, you can call `Export-ADTEnvironmentTableToSessionState -SessionState $PSCmdlet.SessionState` (assuming you're using advanced functions with CmdletBinding).

I appreciate some might have the desire for this, but importing a module alone simply cannot pollute someone's stack with variables unless they specifically request them, which is why it was set up the way it was.
