### ISSUE TITLE
[Feature] Pass through -ErrorAction variable to command in Invoke-ADTCommandWithRetries

### ISSUE THREAD

**Issue by Mrman1093** [PSAppDeployToolkit/PSAppDeployToolkit#1214]
### Summary of the new feature / enhancement

This would allow the user to set the error action for the command being retried in `Invoke-ADTCommandWithRetries`. Additionally, it would set the default error action to Stop as that is what is defined when loading the module.

The `Get-FileHash` example I added with the `-MaximumElapsedTime` parameter will not throw a terminating error if PowerShell is unable to find the file (due to the connection dropping out). By using this parameter you can set it to throw if the computer is unable to reach the file on the SMB share.

While I only see a need for the `-ErrorAction` parameter, some might find it useful to also have a `-CommandWarningAction` or `-CommandContinue` parameter

### Proposed technical implementation details (optional)

Add this parameter:
```PowerShell
[Parameter(Mandatory = $false)]
[ValidateNotNullOrEmpty()]
[System.Management.Automation.ActionPreference]$CommandErrorAction = $PSCmdlet.SessionState.PSVariable.GetValue('ErrorActionPreference'),
```

and replace the line that runs the command with this;
```PowerShell
return (& $commandObj @boundParams -ErrorAction $CommandErrorAction)
```

Alternatively, this could be used to add the parameter to the `$boundParams` variable:
```PowerShell
$boundParams.Add('ErrorAction', $CommandErrorAction)
```

**Comment by mjr4077au** [comment]
This is borderline making what was meant to be a simple retry command into something convoluted. The next thing people will be after will be to be able to provide an array of exception types for it to catch on and handle, etc. Even the max elapsed time stuff I wasn't keen on because you could just make it sleep for 60 seconds and have 10 retries if you wanted it to wait up to 10 minutes.

**Comment by mjr4077au** [comment]
Apologies, I didn't quite get what the problem was this morning while I was in bed, but `Get-FileHash` is a script module and not a binary module, therefore values like `$ErrorActionPreference` don't make it between module barriers. I've addressed this in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/58b1f60adc1883e94225f06cff1111a6d85ff125, along with some other commits to improve the command further and fix a minor regression we both missed.
