### ISSUE TITLE
Show-InstallationRestartPrompt -CountdownNoHideSeconds - Seconds Value ignored

### ISSUE THREAD

**Issue by 2SR82** [PSAppDeployToolkit/PSAppDeployToolkit#124]
Countdown is always 60 Seconds independent which Value is provided

Show-InstallationRestartPrompt -CountdownNoHideSeconds 180
results in Restart after 60 Seconds.

Toolkit Version 3.6.7
Windows 7

**Comment by amotaz** [comment]
I think the issue here is a slight misunderstanding on how the function works.
-CountDownNoHideSeconds only determines how long the restart prompt is showing with the property that it cannot be hidden. So, your value for -Countdownseconds is kind of like a master countdown, from which the -CoutndownNohideSeconds will grab a piece to set that property of the restart window.
Does that make sense?

Try your function again but with -CountDownSeconds also set to 180.

**Comment by 2SR82** [comment]
You are absolutely right. This was really a misunderstanding from my side.
After setting both values to 180 Seconds, everything is working as expected.
Thanks for the clarification!!
