### ISSUE TITLE
Execute-MSI call in Remove-MSIApplications : Cannot validate argument on parameter 'Path'.

### ISSUE THREAD

**Issue by Latupho** [PSAppDeployToolkit/PSAppDeployToolkit#140]
The issue, I have at hands, first looked like, excute-msi, didn't like a null value fra uninstall string, but it looks like something else when I start to debug. I'm on version 3.6.7 and I'm running `Remove-MSIApplications -name 'Navisworks'`. The error I got from the uninstall log is the following (See attached log file.) 
[Autodesk_Naviswork_2016_EN_01_PSAppDeployToolkit_Uninstall.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/115190/Autodesk_Naviswork_2016_EN_01_PSAppDeployToolkit_Uninstall.txt)

When I do a debug on line 2471 = `Execute-MSI @ExecuteMSISplat` I get the following error at line 2464, where PS ISE have selected this variable `$removeMSIApplication`. Error message I get is the following:

> Execute-MSI : Cannot validate argument on parameter 'Path'. The "($_ -match $MSIProductCodeRegExPattern) -or ('.msi','.msp' -contains [IO.Path]::GetExtension($_))" validation script
> for the argument with value "Autodesk Navisworks 2016 Exporters - 64 bit - English Language Pack (SP1)" did not return a result of True. Determine why the validation script failed,
> and then try the command again.
> 
>  At C:\Users\[username]\Desktop\Autodesk Naviswork\2016.0.0.F\1\SCCM\AppDeployToolkit\AppDeployToolkitMain.ps1:2471 char:188
> 
>  Execute-MSI @ExecuteMSISplat
> 
>
> ~~~~~~~~~~~~~~~~
> CategoryInfo : InvalidData: (:) [Execute-MSI], ParameterBindingValidationException
> FullyQualifiedErrorId : ParameterArgumentValidationError,Execute-MSI
> And about here, I can't fully follow what it talks about, "Cannot validate argument on parameter >'Path'.".

This is about how long I got in trobelohosting this, with the debugging knowledge I have.
If you have anything good for me to try, to help you further, please don't hassetate to ask and I will do my bedst.

**Comment by mmashwani** [comment]
I think the issue actually is in Get-InstalledApplication. That function traverses the Uninstall key in the registry and creates objects that contain key information like ProductCode. The ProductCode is simply the name of the registry subkeys under Uninstall. However, not all entries there are actual ProductCodes. Some of the subkeys are just text names instead of being ProductCodes.

In the latest 3.6.8 beta, I updated the Get-InstalledApplication function so that it verifies something is a ProductCode before it writes that property. Then when the results of this function get used in Remove-MSIApplications, I verify that the ProductCode property actually has a ProductCode before I attempt to use msiexec to uninstall it. So now an invalid argument should not get passed to the Execute-MSI function.
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/bd7867435a01259b080e0e986652a665a5d6bfef

Use the latest 3.6.8 beta and see if your issue is gone. We will be releasing this as the final 3.6.8 version this upcoming weekend.

**Comment by Latupho** [comment]
I thought that to, that Get-InstalledApplication is creating/storing some data in the incorrect format, for further use, but was not able to pinpoint it.
Will have a go with "3.6.8 beta" and get back with a status on how it wend.

**Comment by Latupho** [comment]
Good news. I have two programs from Autodesk, Navisworks and Showcase that both had the issue being uninstalled. Both are now uninstalled
Updated my pull of this repository and tryed from that release. It worked fine.

**Comment by mmashwani** [comment]
This function only uninstalls software that is MSI based. From the log you previously posted, the uninstallstring refers to a setup.exe which does the uninstall, not msiexec. That is why the function probably skips over uninstalling your software because it looks for msiexec in the uninstallstring.

**Comment by Latupho** [comment]
That was the same thought I had, but when I looked in Regstry under uninstall it came up with some MSI installed files. The same did win32_product. But had some issues uninstalling them with MSIexec /uninstall [GUID]. Didn't go deep in this, so can be me, can't say atm.

I will just need to finish up thies deployments this or next week, and then I will dig more in to this.
