### ISSUE TITLE
3.6.8 - Failed check to see if PowerPoint is running in fullscreen slideshow mode. 

### ISSUE THREAD

**Issue by kbhunut** [PSAppDeployToolkit/PSAppDeployToolkit#142]
I'm getting this from some user who are still running Powershell 2.0

```
[Post-Installation] :: Failed check to see if PowerPoint is running in fullscreen slideshow mode. 
Error Record:
-------------

Message        : Cannot find a process with the name "POWERPNT". Verify the pro
                 cess name and call the cmdlet again.
InnerException : 

FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Command
                        s.GetProcessCommand

PositionMessage : 
                  At C:\windows\ccmcache\4\AppDeployToolkit\AppDeployToolkitMai
                  n.ps1:8626 char:58
                  +                 [boolean]$IsPowerPointRunning = [boolean](G
                  et-Process <<<<  -Name 'POWERPNT' -ErrorAction 'Stop')



	Test-PowerPoint	2/5/2016 8:17:22 AM	157416 (0x266E8)
```

**Comment by mmashwani** [comment]
You'll need to provide some more details. I don't understand what the problem is. If POWERPNT is not running, then function will return $false. If you use Get-Process to look for a process that does not exist, that cmdlet throws an error. It has nothing to do with the version of PS on the system.

I could hide the error from the logs if that process does not exist but I'm not sure if you're referring to that or something else as the problem.

**Comment by mmashwani** [comment]
I just updated the function so that it handles the error a little better. Try it now and see if you still see the same thing. If so, then I'll need more details from the log, etc.
