### ISSUE TITLE
Set-ActiveSetup Function

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#144]
When the -StubExePath and -Parameter have lengh more than 255, the created VBS have not complete content and the script produces an error.

**Comment by amotaz** [comment]
Hi Cyborgrd,
Can you provide some more detail:
what do you mean by "the created VBS" what vbs are you talking about?

**Comment by amotaz** [comment]
Actually, I see what you're talking about. The vbscript generated during Execute-ProcessAsUser. Ok, I'm investigating.

**Comment by amotaz** [comment]
Ok so a couple of things:
Windows API has a [max_path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx) setting of 260. This can be overcome with various tricks changing the format to unicode and such, but this will make the function needlessly complicated. The simpler solution is to use a shorter path. 

Secondly, your statement that the vbscript has incomplete content worries me. Please paste a copy of the vbscript that is created by your function as well as log files generated by your execution of this script so I can see what's causing the vbscript to not be created correctly.

Thank you

**Comment by mmashwani** [comment]
@cyborgrd 
Hi, any update on this issue?

**Comment by amotaz** [comment]
Any update on this issue cyborgd?

**Comment by cyborgrd** [comment]
Hi, it is another problem. On all functions which used VBS is the same issue. I cannot set taget path (RunProcessAsUser, SetActiveSetup) with quotas like `"$path\file.ext`". The created VBS will not work.

**Comment by cyborgrd** [comment]
``"$path\file.ext`"`

**Comment by amotaz** [comment]
Ok, can you give an example please, of how you're forming your function call. And a log file out put as well would help

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/set-activesetup-function/1222

**Comment by luki1412** [comment]
This must have been fixed in one of the releases. Testing this on 3.8.3. The only thing that breaks our commands are long paths that windows doesnt really care about, unless you specify them in the long format. However that is a toolkit-wide issue. Below Im using Set-Active setup as SYSTEM so it uses Execute-ProcessAsUser to start powershell with a really long parameter and it works just fine. Some characters get lost in transit which I will look into but that might not be avoidable with the current way the function works.
![test](https://user-images.githubusercontent.com/20016096/107029346-2b666280-67af-11eb-8dfd-7240854b2b7b.png)
