### ISSUE TITLE
Set-RegistryKey doesn't handle keys or values with Forward Slashes

### ISSUE THREAD

**Issue by macxcool** [PSAppDeployToolkit/PSAppDeployToolkit#158]
Set-RegistryKey won't handle key names with forward slashes. This happens sometimes when Path names are stored in the registry

Example:
`Set-RegistryKey -Key "HKLM:\SOFTWARE\Dummy\C:/Temp"`
   _creates Dummy\C:\emp and Dummy\C:\Temp_
or:
`Set-RegistryKey - Key "HKLM:\SOFTWARE\Dummy\C:/Temp" -Name 'Something' -Value 'Else'`
   _does the same as above, except this error:_

> Cannot find path 'HKEY_LOCAL_MACHINE\SOFTWARE\Dummy\C:/Temp' because it does not exist.

but this works:
`Set-RegistryKey -Key "HKLM:\SOFTWARE\Dummy" -Name 'Path' -Value 'C:/temp'`

I understand that powershell doesn't differentiate between / and \ when it looks at paths. Is there some way to sanitize this or use .NET for key names that have a forward slash. I've tried putting in the unicode character instead, but it makes no difference.

**Comment by macxcool** [comment]
This seems to work:
```
[Microsoft.Win32.Registry]::LocalMachine.CreateSubKey('SOFTWARE\Dummy')
[Microsoft.Win32.Registry]::LocalMachine.CreateSubKey('SOFTWARE\Dummy\c:/Temp')
[Microsoft.Win32.Registry]::SetValue('HKEY_LOCAL_MACHINE\SOFTWARE\Dummy\c:/Temp','Path','s:/')
```

**Comment by macxcool** [comment]
```
$keyName = 'Software\SoftPlan Systems Inc.\SoftPlan Workstation\16.3.4\C:/Program Files/SoftPlan2014\SoftPlan Folders'
[scriptblock]$HKCURegistrySettings = {
    [Microsoft.Win32.Registry]::Users.CreateSubKey("$($UserProfile.SID)\$($keyName)")
    [Microsoft.Win32.Registry]::SetValue("HKEY_USERS\$($UserProfile.SID\$($keyName)",'Projects','s:/')
    Start-Sleep -Seconds 3
}
Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $HKCURegistrySettings
```

**Comment by macxcool** [comment]
I've attached a Set-RegistryKey that seems to work.
[Set-RegistryKey.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/199798/Set-RegistryKey.txt)

**Comment by amotaz** [comment]
Thanks for the info. I'm looking into this now. I think it would be better to put this in the convert-registry function so that it supports all of the other registry functions, however that means it will need to be thoroughly tested. I'll let you know when I've pushed a change.

**Comment by amotaz** [comment]
I added a change for this to the 3.6.9 version, please test and let me know how it goes.

**Comment by macxcool** [comment]
I've verified that this works now for my scenario.

**Comment by amotaz** [comment]
awesome, thanks

**Comment by kaiserschloss** [comment]
I know this issue is closed, but I am having an issue with forward slashes in a registry key under HKCU.
When replacing the / with [char]0x2215, I get a different, slightly smaller forward slash.  The Java app that I am installing doesn't like the path created and doesn't read the values stored.
When I export the reg keys created, the slash is different.
Key created by the app:
controllers./Data/Controller
Key created by the deployment toolkit:
controllers.∕Data∕Controller

[CreatedByApp.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/1023509/CreatedByApp.txt)
[CreatedByToolkit.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/1023508/CreatedByToolkit.txt)

It is clearly working for others, but there are some cases where it is not working.
