### ISSUE TITLE
Set-ActiveSetup problem when running install as SYSTEM

### ISSUE THREAD

**Issue by Charlz1** [PSAppDeployToolkit/PSAppDeployToolkit#174]
This is with version 3.6.8

When I use PSADT to install an application using Set-ActiveSetup with the SYSTEM account, I get an error at the step where it tries to execute the active setup for the currently logged on user.

I get an error about "Unterminated string constant", similar to issue #22. There is an extra double quote (") in the VBS script.

I also see that issue #22 was reference in issue #38 but I still don't get how I'm supposed to use Set-ActiveSetup if it's working as intended? There is clearly an extra " in the resulting VBS script that is causing this failure.
On another note, the installation still says that the installation was successful even though the VBS file script did not run correctly. Is this normal?

Thank you.

**Comment by Charlz1** [comment]
Hello,
After reviewing the code and checking examples provided for Execute-ProcessAsUser, I modified the following line for the Set-ActiveSetup function:
``[string]$CUArguments = "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -File `"$StubExePath`""``
into this
``[string]$CUArguments = "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & `\`"$StubExePath`\`"; Exit `$LastExitCode }"``

As you can see I also had to add extra \  to $StubExePath because my path has spaces in it...

Can someone comment on the validity of my "fix" or would I break something else with this modification?

Thank you.

**Comment by Charlz1** [comment]
Ok after further reviewing the code, I have made the following changes to my AppDeployToolkitMain.ps1 file and now it seems to work fine.

I have to modify the arguments given to Execute-ProcessAsUser if it's a powershell script.
I have added the following to adapt the parameters when it is a powershell script. It works fine for my installation but I would like to get some feedback from other people using Set-ActiveSetup with PowerShell scripts.

```powershell
If ($CUArguments) {
	
	## If powershell script, adapt parameters for Execute-ProcessAsUser
	if($StubExeExt -eq '.ps1'){
		[string]$CUArguments = "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & `\`"$StubExePath`\`"; Exit `$LastExitCode }"
	}

	Execute-ProcessAsUser -Path $CUStubExePath -Parameters $CUArguments -Wait -ContinueOnError $true
}
```

This needs to be changed at 2 different places in the function because of how the function handles session 0.

**Comment by amotaz** [comment]
Thanks for the code suggestion, I've added it to the toolkit. Please test and confirm the fix.

**Comment by serancti-nurun** [comment]
Write test for new user of forum

**Comment by serancti-nurun** [comment]
Hi everybody !
I use now the PSADT v. 3.6.8 with Windows 8.1 x64

I have the same issue discussed in post #22 , #38 and this one. Only in the case of exploitation of Activesetup / Stubpath when i deploy a package (like Greenshot app or other) with SCCM 2012 with SYSTEM account  (equivalent to session 0, but i am already login in a another user session in the same time, to see the final result of my installation.) A badly formatted PSAppDeployToolkit-ExecuteAsUser.vbs  script is generated in a folder "C:\Users\Public\PSAppDeployToolkit". Gives an execution error caused by an extra " at the end of the first line of this VBS.
To test, I manually edited the .vbs script by changing the last character of the first line. I replaced the "" with " & chr(34) . It works well now and does what contains the line.
Because an chr(34) is missing.

I think I found the solution. Too simple i think
Go to edit the \AppDeployToolkit\AppDeployToolkitMain.ps1 script file (the Core) and point at line number 4539 (to end of this line) in the function "Execute-ProcessAsUser".
Replace the last + '"'  by  + ' & chr(34)'  and saved it.

Like this with complete line...
[string]$executeProcessAsUserParametersVBS = 'chr(34) & ' + "`"$($Path)`"" + ' & chr(34) & ' + '" ' + ($Parameters -replace '"', "`" & chr(34) & `"" -replace ' & chr\(34\) & "$','') + '"' 

replaced by...
[string]$executeProcessAsUserParametersVBS = 'chr(34) & ' + "`"$($Path)`"" + ' & chr(34) & ' + '" ' + ($Parameters -replace '"', "`" & chr(34) & `"" -replace ' & chr\(34\) & "$','') + ' & chr(34)'

Well, for my immediate needs, i changed it and all works well now (no vbs error and execute it fine the activesetup with SYSTEM account in sccm deploy context).

In hope to see this correction in the next version 3.6.9 of PSADT
Serge A, from Quebec City in Canada.

**Comment by PLogFinder** [comment]
I have a slightly different solution that also worked - did not lose (-replace) last quote, and does not put another quote if one is not needed.  I am putting text here then picture, to make sure you can see what was meant (html might lose/change some characters - I'd copy and paste from html, then use the picture to fix it up).
Line 4539:
[string]$executeProcessAsUserParametersVBS = 'chr(34) & ' + "`"$($Path)`"" + ' & chr(34) & ' + '" ' + ($Parameters -replace '"', "`" & chr(34) & `"") + '"'
![image](https://cloud.githubusercontent.com/assets/22904190/19466120/9937daf0-9554-11e6-9cde-e937d3ff5d26.png)
Explanation: buggy line: left me with this data (at the end):  
... " -LogFile " & chr(34) & "C:\OurLogs\file.log""
Fix leaves me with this data (at the end): 
... " -LogFile " & chr(34) & "C:\OurLogs\file.log" & chr(34) & ""

The final quoted empty string is OK/immaterial, and allows the clean completion after automating quote replacement with this combo: (suspend-string QUOTES re-open-string), and without losing or adding extra chr(34).  I think serancti-nurun's solution will work if the last argument used quotes, but maybe not if it's a bare text argument.
