### ISSUE TITLE
Centralizing PSAppDeploymentToolkit

### ISSUE THREAD

**Issue by freedbygrace** [PSAppDeployToolkit/PSAppDeployToolkit#183]
Hey guys!

First, just let me say thank you for developing and doing such great work on this toolkit! It makes it easier to deploy applications seeing as most applications these days require multiple steps, prereqs, etc... and SCCM and MDT do not allow you to natively do this without creating multiple applications and chaining those applications together in bundles which gets cumbersome very quickly. Anyways, this is what I view as an issue.

The centralization of PSAppDeploymentToolkit...

This is already talked about here > [http://psappdeploytoolkit.com/forums/topic/centralizing-the-toolkit/](url)

My question is though, can a change be made in the next update that simply allows you specify the paths as arguments? Via the PS1 or the EXE. Doing it ourselves works just fine until a new version comes out and these changes are required again and again. The discussion from the link above details on how to update static paths and so forth.

My proposal is just arguments with default values. The default values can be how you guys currently have it setup inside the various scripts and modules. But those values will only apply if the arguments values are [String]::IsNullOrEmpty($StringValue).

[Parameter(Mandatory=$false)]
[string]$ScriptDirectory = "$($MyInvocation.MyCommand.Definition | Split-Path -Parent)",
[Parameter(Mandatory=$false)]
[string]$ModuleAppDeployToolkitMain = "$($ScriptDirectory)\AppDeployToolkit\AppDeployToolkitMain.ps1",

Somehow the same logic would be reflected inside of the exe, that would be great.

**Comment by mipbr2000** [comment]
Hey guys!

First, just let me say thank you for the developing.
But please make this feature available. Its so messy the way it is now.
Again, I'm so glad for your app.

**Comment by That-Annoying-Guy** [comment]
Since all of the Maintainers/Developers seem to be on holidays or too busy with their day job, I can help you a bit. Also I am not a Developer. I am just a PSADT user like you. I just report bugs and propose changes.

First of all, **_I do not recommend doing this_** because it creates a single point of failure for all your centralized packages and all previously known good/working packages would need to be re-tested to make sure nothing broke. 

## **DISCLAIMER: The following proposed changes are at your own risk regardless of clarity or errors.**

If I had to do this, I would look at this line in **Deploy-Application.ps1**

	[string]$moduleAppDeployToolkitMain = "$scriptDirectory\AppDeployToolkit\AppDeployToolkitMain.ps1"

Change it to something like this:

	[String]$CentralPSADTDirectory = "\\<ServerName>\<Sharename>\CentralPSADT\AppDeployToolkit"
	[string]$moduleAppDeployToolkitMain = "$CentralPSADTDirectory\AppDeployToolkit\AppDeployToolkitMain.ps1"

Then on your network in the "\\\\<ServerName>\<Sharename>\CentralPSADT\AppDeployToolkit\" folder, copy in all the files from **a**  \AppDeployToolkit\ folder of your choosing.

After this change I don't know what could break.

I still think this will still apply:
$scriptDirectory	=  Folder of Deploy-Application.ps1
$scriptRoot	=  Folder of AppDeployToolkitMain.ps1

## DISCLAIMER: If these changes break things don't blame me or any of the Maintainers/Developers of PSAppDeployToolkit.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/centralizing-psappdeploymenttoolkit/1242

**Comment by mjr4077au** [comment]
This will be feasible with v4 as the backend is module-based, however our current stance is to still statically ship the backend with the frontend for a consistent deployment experience. A public preview of v4 is due out soon where you can test this functionality.
