### ISSUE TITLE
Toolkit Variables not working with Copy-Files

### ISSUE THREAD

**Issue by Kevinnns** [PSAppDeployToolkit/PSAppDeployToolkit#19]
Hi,

I'm using the latest version (3.6.3 beta) and it seems that i've found a little problem.
When wanting to copy a file from the Files directory i get an error:
```
[Installation] :: Failed to copy file(s) in path [$dirFiles\java.settings.cfg] to destination [C:\ProgramData\Oracle\Java\java.settings.cfg]. 
Error Record:
-------------

Message        : Cannot find path 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\$
                 dirFiles\java.settings.cfg' because it does not exist.
InnerException : 

FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemComm
                        and

PositionMessage : 
                  At C:\WINDOWS\ccmcache\53\AppDeployToolkit\AppDeployToolkitMa
                  in.ps1:2869 char:14
                  +                 Copy-Item <<<<  -Path $Path -Destination $d
                  estination -Force -ErrorAction 'Stop' | Out-Null



	Copy-File	30-04-2015 14:44:35	2148 (0x0864)
```
Debunking that, i've ran the Copy-File command *.* destination C:\ProgramData\Oracle\Java\java.settings.cfg. That works just fine (i get alot of files ie. powershell.exe).

It looks to me that when you use variables like $dirFiles and in my case $envProgramData the task fails.

So maybe the first question i have to ask is; Should Copy-Files be able to use toolkit variables?

**Comment by mmashwani** [comment]
I can't be sure as you did not share the original code you have in your script for calling the Copy-Files function, but I think you're using single quotes instead of double quotes around text that contains variables. Single quotes around a variable name means that you wish PowerShell to interpret the text exactly as written. Double quotes means that PowerShell should expand the variable to the value that it contains. Please make sure this is not the problem. Otherwise, you will need to share the original code you have so we can see what is going on.

Also, I edited your post to put the log contents into a code block so that it is easier to read. If you post any code or log file contents, put them in a code block. You can do this by entering three back ticks, `, before and after the text that should be in a code block.

**Comment by Kevinnns** [comment]
Hi, sorry... this is the original piece of "code"

```Copy-File -Path '$dirSupportFiles\java.settings.cfg' -Destination '$envProgramData\Oracle\Java\java.settings.cfg' -ContinueOnError $True```

**Comment by mmashwani** [comment]
Yeah, you're using single quotes instead of double quotes. Your code should look like this:
```
Copy-File -Path "$dirSupportFiles\java.settings.cfg" -Destination "$envProgramData\Oracle\Java\java.settings.cfg" -ContinueOnError $True
```

**Comment by Kevinnns** [comment]
Great, didn't know that. Sorry and thanks for the support! :)
