### ISSUE TITLE
AppDeployToolkitMain.ps1 is not UTF-8 BOM encoded - this causes issues with digitally signing the file on non-unicode systems (e.g. Chinese/Japanese)

### ISSUE THREAD

**Issue by sflach** [PSAppDeployToolkit/PSAppDeployToolkit#207]
Hi,

I've noticed that the AppDeployToolkitMain.ps1 file is not UTF-8 BOM encoded. Due to that, if you digitally sign the file, it will not be seen as valid. Any specific reason for this?

**Comment by That-Annoying-Guy** [comment]
It's very easy to change the encoding just by editing with an editor that assumes that UCS-2 LE BOM is everybody's favorite encoding. 

It can be easily changed by editing the file and changing the encoding.
I use Notepad++ for encoding issues because it's straightforward and easy to use.
-Encoding menu -> Convert to UTF-8-BOM
-SaveAs ...

Good luck.

**Comment by sflach** [comment]
Thanks!

That's exactly what I did. Just wanted to share it here.

**Comment by mmashwani** [comment]
This issue should be resolved in the next release.
