### ISSUE TITLE
Variablelist in documentation

### ISSUE THREAD

**Issue by Hedkandi** [PSAppDeployToolkit/PSAppDeployToolkit#268]
In the documentation you can find $envCommonPrograms which should point to "C:\ProgramData\Microsoft\Windows\Start Menu\Programs". Using this your files ends up in C:\ as the variable does not exist and im using "$envCommonPrograms\File" which results in \File.

Looking in the Main.ps1 file i could see that the documentation should say $envCommonStartMenuPrograms.

**Comment by bruckect** [comment]
This was a BREAKING CHANGE in 3.6.9:
BREAKING CHANGE, Changed variable envCommonPrograms to envCommonStartMenuPrograms

It looks like it was not updated in the documentation. Would you like to submit a Pull Request for the Word Doc? If not, I can.

**Comment by Hedkandi** [comment]
Please do, I am still in the process of learning git.

**Comment by LMCO-psadt-devs** [comment]
**Why is PSADT not striving to be backwards compatible?**

Our company (like many others) has numerous complex deployments that are updated when newer versions of software are released.
We would love to able to copy the already defined Deploy-Application script (modifying only the appropriate variables ...  `$appVersion, $appScriptVersion, $appScriptDate, $appScriptAuthor`) from the deployment for the previous version and incorporate the AppDeployToolkit from the latest PSADT release. 

With this latest release there are both variables and cmdlet parameters that no longer exist.
This makes for reuse (_scripter's best friend_) impossible.

For this specific example ... I am not sure why there was even a need to rename the original variable.
The actual registry entry is '_Common Programs_' which aligns with the original name and matches the naming convention of all of the other variables that are retrieved from the '_User Shell Folder_' registry key.

If there was indeed a valid reason for this change,  PSADT could still have kept `$envCommonPrograms`  and just assigned it the same value as `$envCommonStartMenuPrograms`.

**Please rethink your logic for future releases to ensure backwards compatibility.
We don't want to have to re-engineer our deployments to meet the arbitrary deprecated changes in every release of PSADT.**

**Comment by sintaxasn** [comment]
Hi there,

This particular variable was introduced in the previous release and was labelled incorrectly. An issue was logged about it and thus, we updated the variable to be more descriptive, to CommonStartMenuPrograms, as CommonPrograms could also be confused with C:\Program Files\Common Files. This is also why we didn't keep both variables.

Since the first public release (v2.0) in July 2013, we have only made two changes that affected backwards compatibility (one in v3.0, and this specific change). In fact we have specifically make numerous efforts to keep backwards compatibility across versions when variables and functions become deprecated. PSAppDeployToolkit was built by scripters, for scripters so we understand these requirements.

We plan to keep this up going forward.

Thanks, Dan

**Comment by amotaz** [comment]
The documentation has been updated, thanks for the catch. Please verify. We do not accept pull requests for .docx files due to the risk. 

As Dan said, we strive for backwards compatibility but will make compromises on rare occasions, we're only human. Feel free to point out changes that you believe could have an impact on your processes during our build phase for new versions.

**Comment by regispicanco** [comment]
In documentation, the variable $envCommonStartUp is described as been "C:\ProgramData\Microsoft\Windows\Start Menu", which is the descripttion of the variable $envCommonStartMenu
The correct description of the variable $envCommonStartUp should be "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup"

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
