### ISSUE TITLE
Show-InstallationRestartPrompt's [Restart Later] button does nothing

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#276]
If you call the Countdown-to-Reboot GUI from inside Deploy-Application.ps1:

`Show-InstallationRestartPrompt -Countdownseconds 600`

This calls AppDeployToolkitMain.ps1 a second time to display the Countdown-to-Reboot GUI without blocking Deploy-Application.ps1 that called it.
This works fine but the [Restart Later] button just minimizes the GUI and the countdown timer keeps on going.

This calls AppDeployToolkitMain.ps1 a second time as a separate instance to display the Countdown-to-Reboot GUI without blocking Deploy-Application.ps1 that called it.

I managed to get a debugger going on the second instance that Show-InstallationRestartPrompt creates and this is the problem code:

```
		[scriptblock]$buttonRestartLater_Click = {
			## Minimize the form
			$formRestart.WindowState = 'Minimized'
			## Reset the persistence timer
			$timerPersist.Stop()
			$timerPersist.Start()
		}
```

It turns out for some reason, $timerPersist just stops existing or is just not accessible from the code block.
```
[DBG]: PS> $timerPersist.Stop()
You cannot call a method on a null-valued expression.
At line:1 char:1
+ $timerPersist.Stop()
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

## Solution
```
		[scriptblock]$buttonRestartLater_Click = {
			## Close the form
			$formRestart.Close()     #does nothing
			Start-sleep -Milliseconds 500
			$formRestart.Dispose() #Nuclear option works!
			Start-sleep -Milliseconds 500
		}
```

This works but it does not exit the script as gracefully as I would have wished.
This line causes an error:
`[Microsoft.VisualBasic.Interaction]::AppActivate($powershellProcess.ID)`

For myself, I wrapped it in a try/catch but I think it's a sloppy solution. I'm hoping someone can come up with a better workaround.

**Comment by seanlillis** [comment]
Actually, this behaviour is by design. You can opt to use the Show-InstallationRestartPrompt with a countdown or without a countdown to a forced reboot. If you opt to use a countdown it's because you want to force a reboot to happen, there is no backing out. In both scenarios, the restart later button only minimizes the dialog, that's all it was ever intended to do, not to close the restart prompt altogether or to kill the countdown timer. The $timerPersist variable is then supposed to be reset so that the dialogue waits for the full timer persistence duration again before it is brought back in to focus. If you are looking for different behavior, you can raise it as a feature/enhancement request rather than an issue.

**Comment by That-Annoying-Guy** [comment]
Then it is bad design. As a user I would feel duped if I click on  [Reboot Later] button and the computer still reboots on me without warning.
Please rename the button to [Minimize Me] or [Get out of my way but will still reboot].

Regardless, I would still prefer to have a [Reboot Later] button as an option. I had to modify things to give the user the choice to reboot later but still warn them that the newly installed app would not work until the reboot. 

PS: How do I know if you will use/have used my pull request? should I have made multiple forks and create pull requests from each for each Issue?

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-installationrestartprompts-restart-later-button-does-nothing/1191
