### ISSUE TITLE
Execute-ProcessAsUser help example produced an error -196608

### ISSUE THREAD

**Issue by appPackager** [PSAppDeployToolkit/PSAppDeployToolkit#28]
When using the Execute-ProcessAsUser help example as stated I get an error reported back to the log file.
Original Example:
Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters 
    '-File `"C:\Test\Script.ps1`"; Exit `$LastExitCode' -Wait

Changing the examples to the following variation resolved my issue:
Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters 
   '-File "C:\Temp\Script1.ps1" Exit $LastExitCode' -Wait

**Comment by mmashwani** [comment]
The problem with what your change is that you are now telling powershell.exe to exit with the actual value of LastExitCode as it currently stands when the command was executed. You would not get the correct exit code back from the execution of the Script1.ps1. Also, the semi-colon is required so that powershell.exe knows that these are two separate commands you are executing.

Thinking about it, I think the example should really be like so:
```
Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters '-Command `"C:\Test\Script.ps1`"; Exit `$LastExitCode' -Wait
```

I think there is a bug around the -File parameter for powershell.exe. It can't accept script blocks so the Exit command won't work with it. It also does not return the correct exit code and that bug will never be fixed due to Microsoft being super anal about maintaining backwards compatibility.

**Comment by appPackager** [comment]
Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters '-Command `"C:\Test\Script.ps1`"; Exit `$LastExitCode' -Wait

In performing further testing it appears that replacing "-file" with "-command" solves part of the issue but not all. When using the new command-line I now get a failure code: 1. 

If I remove the escape (`) characters within the string I get success:
Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters '-Command "C:\Test\Script.ps1"; Exit $LastExitCode' -Wait

**Comment by mmashwani** [comment]
I'm concerned that the above command will not exit with the correct exit code from the execution of Script.ps1 if that script were returning some custom exit code. I have not tested the below command, but I think it should work and it would guarantee that we get the correct exit code passed back to the task scheduler because the $LastExitCode variable would be enclosed in a script block. Basically, what I want to be able to do is not pass the value of the $LastExitCode variable from the current script to the exit statement of the script I want to execute as that would mean that exit code information from the script being executed would be lost. I hope that makes sense and this might not be useful for you in the case of this script, but it may be important in other instances.

```
Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command & { & `"C:\Test\Script.ps1`"; Exit `$LastExitCode }" -Wait
```

**Comment by appPackager** [comment]
I tried your last example and it works flawlessly.  The psappdeploytoolkit log file logs an exit code of 0 upon successful execution of script.ps1 and also returns the proper error code from the script.ps1 when demanded. Can your latest example be added to Execute-ProcessAsUser help in place of the current?

**Comment by mmashwani** [comment]
It's been updated in the latest beta.
