### ISSUE TITLE
Strange behavior with Show-InstallationPrompt, NoWait parameter and message with double quotes

### ISSUE THREAD

**Issue by lucafabbri365** [PSAppDeployToolkit/PSAppDeployToolkit#297]
PSAppDeployToolkit version 3.6.9.

If I use **Show-InstallationPrompt** function inside my **Deploy-Application.ps1** with a message containing double quotes and _-NoWait_ parameter, the double quotes won't be displayed on rendered window. If I omit the parameter, they are displayed.

_Example (no double quotes displayed):_
`Show-InstallationPrompt -Message "My name is ""Luca""" -ButtonRightText "OK" -Icon "Information" -NoWait` or `Show-InstallationPrompt -Message 'My name is "Luca"' -ButtonRightText "OK" -Icon "Information" -NoWait`

_Example (double quotes displayed):_
`Show-InstallationPrompt -Message "My name is ""Luca""" -ButtonRightText "OK" -Icon "Information"` or `Show-InstallationPrompt -Message 'My name is "Luca"' -ButtonRightText "OK" -Icon "Information"`

Can you check this behavior ?

**Comment by seanlillis** [comment]
The quotes are lost when running asynchronously due to the way the toolkit has to take parameters passed to functions that were specified to run asynchronously, format the parameters as a string and pass those to a new instance of PowerShell. Unfortunately, there is no easy way to preserve the quotes when they go through this process.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/strange-behavior-with-show-installationprompt-nowait-parameter-and-message-with-double-quotes/1185

**Comment by mjr4077au** [comment]
This has been fixed in v4.
