### ISSUE TITLE
show-installationwelcome does hide program to be installed in case apps need to be closed

### ISSUE THREAD

**Issue by chrisbru** [PSAppDeployToolkit/PSAppDeployToolkit#307]
Hi,
I am using show-installationwelcome with the -closeapps and the -ForceCountdown switch.
When no apps need to be closed, the popup for the user window starts with:
"the following application is about" to be installed : xxxxxx"
Perfect. So far so good.

However, when there are apps which need to be closed this above message line is concealed and the
windows text starts with:
"The following programs must be closed before the installation.....", hiding the
application name which is to be installed.
See attached picture.

Can this be fixed, so that "the following application is about" to be installed : xxxxxx" appears in 
every case?

Thanks and best regards,
Chris

![psadt](https://user-images.githubusercontent.com/32386336/31178631-f73fb3c8-a919-11e7-822a-a8ccf19500d7.JPG)

**Comment by seanlillis** [comment]
Hi, this is by design. Those are the default messages displayed for those dialogs based on keeping the amount of message text proportionate to the dialog.

If you wish, you can modify the message text in the XML file, or alternatively you could modify the default messages that are used in those dialogs in the toolkit code.
