### ISSUE TITLE
Setting executionpolicy to allsigned with GPO problem

### ISSUE THREAD

**Issue by Robert-LTH** [PSAppDeployToolkit/PSAppDeployToolkit#310]
When setting the executionpolicy to allsigned with GPO and run Deploy-Application.exe, you get nothing as output. C:\windows\logs\software is not populated with any log saying anything.

Luckily eventviewer has a record stating:
"Error Message = Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy"."

But even when you require signed scripts and you have an invalid signature or no signature, you dont get an error or log from Deploy-Application.exe.

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/4884ddcdf1a98c185ce6fae2a84a9f05b0917b4f/Sources/Deploy-Application/Deploy-Application/DeployApplication.cs#L25

**Comment by Skylancer187** [comment]
I've been using the PSDTK for about 2 years now. PowerShell is a bit tricky with the execution policy. It all depends on the scope that you set the policy for. Naturally since most of the PSDTK runs without a terminal or host window, you won't get any feedback or errors for Signature/Execution Policy issues.

I set the following User, Local, SCCM and Remote Scopes to AllSigned within my entire environment. This ensures better protection against Rouge Malware and/or crafty users.

When I sign the Deploy-Application.ps1 and all of the Support and Main *.ps1 files, I never have issues. We use a PKI CA within our environment to validate trust. However you don't need a CA Root to do this. You can generate a generic Certificate on your development workstation and Export the public key. Take the public key and deploy it to your desired devices' certificate store under:
Cert:\LocalMachine\TrustedPublisher\

Then sign all of your scripts with that Certificate and you'll be set. Be sure to make a backup of the private key and protect the certificate from non-authorized personnel.

If you ever suspect that you're script isn't working when you have AllSigned Scopes turned on; sign all of the scripts and support files again.

**Comment by Robert-LTH** [comment]
My problem is not that my script is not signed, my problem is that i dont get any logs from deploy-application.exe

Med vänlig hälsning,
Robert Johnsson



On Sun, Nov 5, 2017 at 3:32 AM +0100, "Skylancer187" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been using the PSDTK for about 2 years now. PowerShell is a bit tricky with the execution policy. It all depends on the scope that you set the policy for. Naturally since most of the PSDTK runs without a terminal or host window, you won't get any feedback or errors for Signature/Execution Policy issues.

I set the following User, Local, SCCM and Remote Scopes to AllSigned within my entire environment. This ensures better protection against Rouge Malware and/or crafty users.

When I sign the Deploy-Application.ps1 and all of the Support and Main *.ps1 files, I never have issues. We use a PKI CA within our environment to validate trust. However you don't need a CA Root to do this. You can generate a generic Certificate on your development workstation and Export the public key. Take the public key and deploy it to your desired devices' certificate store under:
Cert:\LocalMachine\TrustedPublisher\

Then sign all of your scripts with that Certificate and you'll be set. Be sure to make a backup of the private key and protect the certificate from non-authorized personnel.

If you ever suspect that you're script isn't working when you have AllSigned Scopes turned on; sign all of the scripts and support files again.

**Comment by Skylancer187** [comment]
Consider setting up a simple Script Signing process. It's relatively easy!
1. Create the Cert and Export Public Key.
2. Deploy via GPO or BAT, place the Cert in the Trusted Publisher Store of Local Machine.
3. Sign scripts with private cert/key.
4. Deploy Script with Signed Code and never have an issue.

You can get some details from the 'Scripting Guy' on TechNet: (It's for a PKI CA Root, but it's got the general details)
https://blogs.technet.microsoft.com/heyscriptingguy/2010/06/16/hey-scripting-guy-how-can-i-sign-windows-powershell-scripts-with-an-enterprise-windows-pki-part-1-of-2/
https://blogs.technet.microsoft.com/heyscriptingguy/2010/06/17/hey-scripting-guy-how-can-i-sign-windows-powershell-scripts-with-an-enterprise-windows-pki-part-2-of-2/

Here is a TechNet script to create a Self Signed Cert:
https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6

All I'm going to say is that PowerShell is only going to get more popular. Prevent malicious scripts from wrecking havoc!

Once you have a signing cert, you can sign all the PSDTK Help and Support Files then saving those in a good location. You can use those as a template as they don't need to be touched or managed often. Then all you have to sign is the Deploy-Application.ps1 for each application as needed.

**Comment by Skylancer187** [comment]
As a reminder:
"Naturally since most of the PSDTK runs without a terminal or host window, you won't get any feedback or errors for Signature/Execution Policy issues. When you use the Execution Policy AllSigned, a Bypass normally won't work within that context of the Scope it's being executed."

So, no you won't get any output or errors if the script isn't signed and executed with Execution Policy set to AllSigned.

**Comment by Robert-LTH** [comment]
A simple exitcode if the deploy-application.ps1 didnt run would be sufficient.

I know how to sign scripts and i have signed my scripts, next level to this is when you sign your script but dont have an applocker policy set but i guess i will sort this myself. Thanks anyways.

Med vänlig hälsning,
Robert Johnsson



On Wed, Nov 8, 2017 at 3:21 AM +0100, "Skylancer187" <notifications@github.com<mailto:notifications@github.com>> wrote:


As a reminder:
"Naturally since most of the PSDTK runs without a terminal or host window, you won't get any feedback or errors for Signature/Execution Policy issues. When you use the Execution Policy AllSigned, a Bypass normally won't work within that context of the Scope it's being executed."

So, no you won't get any output or errors if the script isn't signed and executed with Execution Policy set to AllSigned.

**Comment by taikuli** [comment]
Unfortunately signing all the .ps1-files did not work for me in this scenario.
AppDeployToolkitMain.cs needs to be signed as well.
Since .cs files cannot be signed, it must be compiled and signed.
Has anybody done that already?

**Comment by mjr4077au** [comment]
The final v4 release will be a digitally signed module, including the C# code which will ship as a DLL file. The deployment script that you modify won't be signed as it's pointless, however.

The remaining discussion points in this issue are to do with `Deploy-Application.exe` logging and/or exit codes in the event of an issue. This specific request is being tracked in #291.
