### ISSUE TITLE
PSADT exitcode not passed if launched by CMD

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#346]
Due to legacy/complacency issues, all my PSADT packages must be launched by a CMD.  (NOTE: This sometimes causes the PS1 Exitcodes to rollover at the 65535 mark but this is not a PSADT issue!)

The issue I'm running into is that the calling CMD always gets exitcode 0 from PowerShell.

I call my Deploy-Application_v1r1.ps1 like this:
`Powershell.exe -ExecutionPolicy Bypass "& '%~DP0Deploy-Application_v1r1.ps1' Uninstall NonInteractive" `

If the Deploy-Application_v1r1.ps1 script runs this command:
`Exit-Script -ExitCode 123`

the PSADT log file will get exitcode 123 but the CMD that called will get exitcode 0. Always 0.

In the beginning my CMD used to work with this:
`REM Powershell.exe -ExecutionPolicy Bypass "& '%~DP0%~n0.ps1' Uninstall NonInteractive"; echo $LASTEXITCODE`

But that has ceased to work in the past year or so but I didn't have time to chase it until last week.
The fix I came up with was by modifying the last line in the **Exit-Script** function.

`If (Test-Path -LiteralPath 'variable:HostInvocation') { $script:ExitCode = $exitCode; Exit } Else { $host.SetShouldExit($exitCode) ; Exit }`

I just don't know if this would break other things.

**Comment by DennisVH** [comment]
Have you tried using -File parameter instead:
`Powershell.exe -ExecutionPolicy Bypass -File "%~DP0Deploy-Application_v1r1.ps1" Uninstall NonInteractive`

**Comment by CosmicSingularity** [comment]
Question: When you say CMD do you mean you are creating an Install.CMD and
Uninstall.CMD, or that you are using the command line rather than
deploy-application.exe?

If using CMD file try this.

Powershell.exe -ExecutionPolicy Bypass "& '%~DP0Deploy-Application_v1r1.ps1'
Uninstall NonInteractive"
@echo %ERRORLEVEL%
set exitCode=%ERRORLEVEL%
exit /b %exitCode%

**Comment by That-Annoying-Guy** [comment]
Using _your_ CMD and the original PSADT code, this is the output I get:

```
[Deploy-Application_v1r1.ps1] ExitCode = 123
1

C:\Windows\system32>set exitCode=1
```

Using _your_ CMD with my modifications to Exit-Script, it returns 123. (Windows 7 and Windows 10)

This being said, one of my co workers used my modifications in a offline network and he **had to revert to the original PSADT code** to get the 123 exitcode. 

So now I'm worried that I have an environmental issue. It could be:
-KB (Aka OS Patch / hotfix)
-GPO
-?!?!

I'm open for ideas as to what can cause this behaviour.
Also, is anybody else running into this or am I alone?

**Comment by TXTechie** [comment]
I'm using the following from a command script (.CMD file) in order to **successfully** (at least for me, on all of our Win7, Win8 & Win10 PCs) pass the PSADT script exit codes back to my .cmd file and then back to my Software Deployment solution:

    Deploy-Application.exe -DeploymentType "Install"
    Set ExitCode=%errorlevel%
    Exit %ExitCode%

However, I'm also receiving an exit code of 65535 from many, but not all, of my Windows 7 PCs but it generates no log so I don't know what is causing the exit code of 65535. The strange thing is that I can execute the same PSADT script command using PsExec (**psexec -s -i**) - which I always heard was a good way to test most Software Deployment (SD) solutions since running PsExec with the **-s** switch is supposed to be basically the same as running with most SD solutions that deploy software using the local SYSTEM account, as our does.

So, I don't know what's going on and I'm not sure how to troubleshoot this and determine what is going on. Does anyone have any ideas?

**Comment by That-Annoying-Guy** [comment]
I don't use Deploy-Application.exe because I don't need it to show GUI stuff to users while running as system.

When I launch PS1 from CMD and PS1 returns an exitcode HIGHER than 65535, the %ERRORLEVEL% **rolls over**! Exitcode 65536 becomes %ERRORLEVEL%=1 and so forth.

I'm suspecting that Deploy-Application.exe just freezes the ERRORLEVEL at 65535.

**Comment by TXTechie** [comment]
I found out what was causing the exit code of 65535 with my Software Deployment (SD) solution. I'm using ServiceUIx86.exe and it's returning an exit code of -1 which either my .CMD script or my SD solution is then interpreting as the maximum of 65535.

I resolved this in another way.

Thanks!

**Comment by That-Annoying-Guy** [comment]
Thank you DennisVH!
I didn't see you comment until a while later.

The solution is to use the -File parameter.

We originally did not use the File parameter because it caused issues with logging and or retrieving the exitcode. This is proof MS is changing PowerShell behind the scenes and not telling anybody.
