### ISSUE TITLE
Unable to see GUI when connected to computer with Remote Desktop

### ISSUE THREAD

**Issue by rsaada** [PSAppDeployToolkit/PSAppDeployToolkit#350]
This has always been a limitation with  PSAppDeployToolkit. The inability to see the user interface whenever connecting to a client computer with Remote Desktop Connection. The install still takes place but without any GUI and sometimes with a long delay as the install times out. Are there any plans to address this in future versions of the toolkit?

**Comment by khaffner** [comment]
We've never had this problem where I work, remoting into multiple VM's dedicated to testing PSADT-scripts. Does running the exact same code locally render some GUI? Is $Deploymode perhaps set to "Silent"? Does the log say anything interesting?

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/unable-to-see-gui-when-connected-to-computer-with-remote-desktop/1156

**Comment by luki1412** [comment]
The GUI is visible when running through Remote Desktop. Depends on how you deploy it. However, I have never had an issue with this, working with it for years. I am closing this issue, because it has been open for almost two years without the author providing any details regarding their issue or proof that there is a bug in the toolkit.
