### ISSUE TITLE
Show-InstallationRestartPrompt does not reboot if -DeployMode "NonInteractive"

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#359]
If you build a Deploy-Application.ps1 with the -DeployMode "Interactive" parameter, the Show-InstallationRestartPrompt function works as advertised.

If you then use -DeployMode "**NON**Interactive", the Show-InstallationRestartPrompt function  just logs
"Bypass Installation Restart Prompt [Mode: NonInteractive]." and exits the function.
**It does not reboot silently.**

I can modify the Show-InstallationRestartPrompt function behaviour for my fork with the code below but I thought this was inconsistent and that I should report it. It's either this or a new function to cause reboot while "NonInteractive".

```
		## Bypass if in non-interactive mode
		If ($deployModeSilent) {
			Write-Log -Message "Bypass Installation Restart Prompt [Mode: $deployMode]." -Source ${CmdletName}
			Write-Log -Message 'Force restart the computer in [$CountdownSeconds] seconds...' -Source ${CmdletName}
			Restart-Computer -Force -wait -Timeout $CountdownSeconds -AsJob # using AsJob to let script shutdown gracefully
			Return
		}
```

**Comment by skinnystick22** [comment]
I have noticed this in some circumstances where I actually used $deploymentType = Silent. It does not reboot or gets hung in the logs while trying to do the reboot.

**Comment by middletonk** [comment]
I believe I've seen the same non-reboot behavior on an interactive deployment when no one is logged in to receive the Show-InstallationRestartPrompt UI popup, though this may be an intentional design choice.

In my case I've considered using Restart-Computer after using Show-InstallationRestartPrompt, as PSADT should have already returned 0 by that point and this built-in cmdlet does not actually restart the PC if anyone is logged in (unless you use the -Force param).

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-installationrestartprompt-does-not-reboot-if-deploymode-noninteractive/1135

**Comment by luki1412** [comment]
Implemented as a parameter for the function. So from the next version onward you will be able to enable rebooting through this function even on silent or very silent deploy mode.
