### ISSUE TITLE
sql server2017- problem with instalation

### ISSUE THREAD

**Issue by borkoew** [PSAppDeployToolkit/PSAppDeployToolkit#378]
Hi, I have problem with silent installation SQL Server 2017.  During installation I get Failed code -Execution failed with exit code [-2068578304] neither with this codes or not -
1)
Execute-Process -Path "$dirFiles\setup.exe" -Parameters " /Q /IACCEPTSQLSERVERLICENSETERMS /ACTION=install /ConfigurationFle=./ConfiguerationFile.ini" -WindowStyle Hidden
2)
Execute-Process -Path "$dirFiles\setup.exe" Parameters " /Q /IACCEPTSQLSERVERLICENSETERMS /ACTION=install /FEATURES=SQL... etc" -WindowStyle Hidden

I would like to install full Features

**Comment by DennisVH** [comment]
@borkoew, when using a ConfigurationFile.ini please use the full path to the file "$dirFiles\ConfigurationFile.ini" instead of ./ConfigurationFile.ini.

About the error message you get, are you trying to install to a compressed or encrypted file location?
https://blog.sqlauthority.com/2017/04/11/sql-server-service-pack-error-attributes-not-match/

Does an non silent installation works without issues?

**Comment by borkoew** [comment]
The SQL doesn’t install. After starting it gets a fault. Adding a full path to the configuration file didn’t work . Code filed it doesn’t change. Silent install it’s ok when i use standard features. I need full features

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/sql-server2017-problem-with-instalation/1126

**Comment by luki1412** [comment]
You're supposed to either use the configuration ini file or put all parameters in the command line. Parameters usually override settings in the configuration file if both are present.

If you want to install all features, remove FEATURES=... and add ROLE="AllFeatures_WithDefaults"

Source: https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt
