### ISSUE TITLE
Execute-MSI -Action "Uninstall" does not respect -Parameters or -Addparameters

### ISSUE THREAD

**Issue by LionZum** [PSAppDeployToolkit/PSAppDeployToolkit#391]
Execute-MSI -Action "Uninstall" does not respect -Parameters or -Addparameters
The executed action is only the default command line

**Comment by DennisVH** [comment]
Can you please provide Excute-MSI commandline used and extract of the log file generated.

**Comment by LionZum** [comment]
#Execute-MSI -Action "Uninstall" -Path "$dirFiles\CylanceProtect_x64.msi" -Parameters "REBOOT=ReallySuppress /QN /L*v `"C:\WINDOWS\Logs\Software\CylanceProtect_x64_Uninstall.log`" UNINSTALLKEY=passwordhere"

I was trying all types of parameters and nothing in parameters was actually used.  I had to do execute-process to get it to pass the parameters.

**Comment by luki1412** [comment]
That's because you used it incorrectly. String starts and ends with quotes. You have 4 double quotes there. Powershell starts reading the string after the second one and then does not know what's path doing there.
You should escape quotes that need to be passed to the msi/exe like this:
**Execute-MSI -Action "Uninstall" -Path "$dirFiles\CylanceProtect_x64.msi" -Parameters "REBOOT=ReallySuppress /QN /L*v `"C:\WINDOWS\Logs\Software\CylanceProtect_x64_Uninstall.log`" UNINSTALLKEY=passwordhere"**

**Comment by MIHSssweeny** [comment]
Execute-MSI -Action "Uninstall" -Path "$dirFiles\CylanceProtect_x64.msi" -AddParameters "UNINSTALLKEY=passwordhere"
I started with this and found it was completely ignored as well.

And I am fairly sure I also did.
Execute-MSI -Action "Uninstall" -Path "$dirFiles\CylanceProtect_x64.msi" -Parameters "REBOOT=ReallySuppress /QN /L*v `"C:\WINDOWS\Logs\Software\CylanceProtect_x64_Uninstall.log`" UNINSTALLKEY=passwordhere"


Didn’t really matter.  No matter what I did it ignored it.
This is ultimately what did work

Execute-Process -Path "msiexec.exe" -parameters "/x $dirFiles\CylanceProtect_x64.msi UNINSTALLKEY=passwordhere REBOOT=ReallySuppress /QN /L*v `"C:\WINDOWS\Logs\Software\CylanceProtect_x64_Uninstall.log`""

**Comment by luki1412** [comment]
I think the issue here isn't the command but the msiexec not liking the input. Execute-MSI appends logging by default. You can override it through the parameter LoggingOptions however if you dont, it will  append /L*v <path> by itself. So if you add it as a parameter, then it will appear twice in the final parameters for msiexec. Also, you should put "REBOOT=ReallySuppress /QN" in the xml config file so this command uses it by default for every msi/msp. It can be overriden later if needed.
-Parameters would override them, -Addparameters would append to the xml params

**Comment by LionZum** [comment]
The only thing I was trying to add was

UNINSTALLKEY=passwordhere

It ignored it.

**Comment by luki1412** [comment]
This function does the same with supplied parameters regardless of Action selected.

```
#  Replace default parameters if specified.
If ($Parameters) { $argsMSI = "$argsMSI $Parameters" } Else { $argsMSI = "$argsMSI $msiDefaultParams" }
#  Append parameters to default parameters if specified.
If ($AddParameters) { $argsMSI = "$argsMSI $AddParameters" }
```

Never had an issue with parameters being ignored if I had my quotes right and escaped. You can check whether your variable is set by looking into the log file created by msiexec. Are you telling me that all your paremeters got ignored including /QN and your installation was not silent?
