### ISSUE TITLE
%windir%\Windows\Logs\Software will probably be wrong directory for logs with Windows 10. (Need to change it)

### ISSUE THREAD

**Issue by Reclad** [PSAppDeployToolkit/PSAppDeployToolkit#410]
Hi everyone,

From one week, we lost our logs directory (set by default with PSAppDeployToolkit to %windir%\Windows\Logs\Software) randomly everyday.
It's a problem because all of our packages use this default directory. And debugging is crucial.

It's probably because of an update from May 2019 (Build 1803). We don't know exactly which update is.

But we are sure that is cleamgr.exe was deleting the folder : 
![image](https://user-images.githubusercontent.com/350119/58428937-67719680-80a4-11e9-85e3-880a05da0bc9.png)

Maybe in next release, we need to change this default folder to another more "cleanmgr proof".

I will probably contact microsoft support to understand if it's a bug or it's a new requirement.

Does anyone see this problem too?

**Comment by paulwetter** [comment]
I have seen that this directory gets cleared when I run an in-place upgrade from one build to the next. Other than that, I have not seen it clear out.
I guess I’ve been ok with it clearing when a feature update is done because it is sort of a new baseline/starting point for the machine.

**Comment by mqmashwani** [comment]
The best practice is to set your log directory to a location in %ProgramData%. The location "%windir%\Windows\Logs..." can get cleared out during upgrades and as part of storage maintenance tasks.

**Comment by Reclad** [comment]
Hi, thanks for reply.

@paulwetter : this folder disappear without any "build" upgrade, that's why it's weird. (And no update too)

@mqmashwani : Yes, we will do that, thank you. Maybe it will be a good thing to place it by default in future version of PSAppDeploy ? :)

**Comment by FRacine** [comment]
We are putting it under c:\programfiles\organisation\logs. Why not just let peoples customizing the location.? Its only a variable.

**Comment by SierraEcoBravo** [comment]
Since both logging for the toolkit and MSI's are variables in the XML, set them to whatever you choose. The defaults are there so it works without alteration.

**Comment by Reclad** [comment]
@FRacine It's not only a variable, it's default or "preferable" location because it's way more logic for us. It was true, but today it's not.

@SierraEcoBravo Yes, I know, I don't talk about how to do change that, i talk about the default logic of PSAppDeployToolkit.

I simply wrote this issue as a suggestion.

(We choose by default C:\Windows\Logs\Software because PSAppDeployToolkit propose it and we thinked that it was the best behavior. We already changed it from all our package.)

**Comment by oem111** [comment]
Hi,
some additonal Infos to this topic if someone is intressted in .

As we also had "lost" some logs in "%Windir%\Logs\Software", we found out that there is a scheduled task in Windows 10, somehow without triggers, but it calls up cleammgr.exe.

We have changed in out test enviroment the following registry-key for Windows 10:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Temporary Files

LastAccess -> 28 (decimal)

Orginal value is 7 (decimal) so that all logs that were not modified since 7 days would be clean by cleammgr.

Within this registry hive the complete folder "%windir%\logs" is marked as section "Temporary Files" for cleanmgr.exe. 

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Temporary Files

Folder -> %temp%|%windir%\Temp|%windir%\Logs...........

So like the other posts recommend it use another location.

**Comment by That-Annoying-Guy** [comment]
We ran into this issue 10+ years ago. The solution was to merge and manage them. 

5+ years ago we found PSADT and had then add a temporary logging folder option (enabled in the XML).
The log files were zipped up into one zip file and the temporary log was deleted.
We have since gone to merging the log files into ONE log file instead of Zipping
We even roll the log files so that multiple attempts can be compared.

**Comment by FRacine** [comment]
Hi,

The best is to change the log path location outside Windows. Easy and no issue.

François Racine

________________________________
De : That-Annoying-Guy <notifications@github.com>
Envoyé : 29 octobre 2019 15:31
À : PSAppDeployToolkit/PSAppDeployToolkit <PSAppDeployToolkit@noreply.github.com>
Cc : FRacine <FrancoisRacine@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [PSAppDeployToolkit/PSAppDeployToolkit] %windir%\Windows\Logs\Software will probably be wrong directory for logs with Windows 10. (Need to change it) (#410)


We ran into this issue 10+ years ago. The solution was to merge and manage them.

5+ years ago we found PSADT and had then add a temporary logging folder option (enabled in the XML).
The log files were zipped up into one zip file and the temporary log was deleted.
We have since gone to merging the log files into ONE log file instead of Zipping
We even roll the log files so that multiple attempts can be compared.

**Comment by oanceaadrian** [comment]
In my organization, we redirect all logs(msi+PSADT) to %windir%\CCM\Logs.
I propose you guys set this as the default since most of the users of PSADT are ConfigMgr admins anyway(probably).

**Comment by Xtraim** [comment]
Hi,

Im not a configmgr admin, the default directory is good for me ;).

Nathanaël LACOURLY

On 10 Dec 2020, at 07:41, oanceaadrian <notifications@github.com> wrote:

﻿

In my organization, we redirect all logs(msi+PSADT) to %windir%\CCM\Logs.
I propose you guys set this as the default since most of the users of PSADT are ConfigMgr admins anyway(probably).

**Comment by luki1412** [comment]
Some people use PSADT under SCCM, some under Intune or other deployment solutions. Sometimes not even for those. We can't assume it is being used for any software, as it might not even be on the machine. The setting is a part of the config file because it is supposed to be configured.

**Comment by Reclad** [comment]
It's old guys ! :) 

But as reminder for people who don't understand this issue : I just talked here about **default** behavior. I repeat : **Default Behavior**. :)
