### ISSUE TITLE
Importing Reg File 

### ISSUE THREAD

**Issue by TekJunki** [PSAppDeployToolkit/PSAppDeployToolkit#432]
Hello there, thank you for the awesome tool. I was running into an issue where I am trying to import a reg file that is for "HKEY_CURRENT_USER."

The issue that I am running into is that the application is being deployed by SCCM under the SYSTEM where the RegKey is for Current User. Can I leverage the use of "Execute-ProcessAsUser" or is there another option that I am not thinking about?

Thank you for your time and help in advance :)

**Comment by macxcool** [comment]
Invoke-HKCUSettingsForAllUsers loads the users's registry hives. You can do that manually or you can import that .reg file inside the scriptblock that runs under this function.

**Comment by GamerZone360** [comment]
Thank you for the detailed information. The reg file contains server connection information so when the application is installed via Software Center and the reg file is imported, it should pre-populate the server tab with the server names. 

I wanted to understand the following "Just make sure that you only target the profiles you want and that the registry file has HKEY_USERS<USER'S SID> instead of just HKCU."

If the application is being made available in the Software Center, anyone can install the application, so there is no way for me to include the SID for users. Unless I am not understanding something correction. 

Appreciate the time and your help with the issue :)

**Comment by macxcool** [comment]
That makes it more difficult. How many registry settings are we talking about? How many lines are in the .reg file. I've done something similar with a huge number of registry settings and just parsed the the .reg file and had the script edit the lines to insert the correct SID for each user. This is available in the $userProfile.SID variable inside the HKCU-Invoke... scriptblock.

**Comment by macxcool** [comment]
Here's an example of how this might look:
```powershell
# Parsing the .reg files and setting up settings for all users. This may take awhile.
            [string]$baseKey = 'HKCU:\Software\NetSupport Ltd\PCICTL'
        [scriptblock]$StuffToDo = {
            # Set the name of the config to use
            Set-RegistryKey -Key $baseKey -Name 'nssCurrConfig' -Value 'NetSupport School' -SID $userProfile.SID

            # Apply all user-specific settings
            Get-Content -Path "$dirSupportFiles\NetSupport_11_Reg_Settings-common.reg" | ForEach-Object {
                [string]$thisLine1 = $_
                # This just splits each line in the .reg file at the '=', gets right of quotes and replaces \\ with \
                $regName1 = $thisLine1.split('=')[0].trim('"').replace('\\','\')
                $regValue1 = $thisLine1.split('=')[1].trim('"').replace('\\','\')
                Set-RegistryKey -Key "${baseKey}\ConfigList\NetSupport School" -Name $regName1 -Value $regValue1 -SID $userProfile.SID
            }
        }
        $goodProfiles = Get-UserProfiles -ExcludeNTAccount "${envComputerName}\TSA"
        Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $StuffToDo -UserProfiles $goodProfiles
```

**Comment by GamerZone360** [comment]
Lol, there is a lot of data in that reg file and I am beginning to think that this was not as easy as I thought. I guess my main issue is that Ia m trying to install the application in System Content and then try to import reg under User Content. Thanks for the example, I will take a look :)

**Comment by macxcool** [comment]
If you post one of the lines from the reg file (are they all similar) I can help you figure out the string processing if you need it.

**Comment by GamerZone360** [comment]
Looking over your example it looks like you are defining the reg information vs just importing it into the hive. The reg file that I have has a lot of info and it would be a painful process for me to have it config it one at a time vs just having the reg file import setting by itself for all the users or at least for the user who is installing the application. 

Let me know if I am off base on my understanding. I will look at the reg that is imported and see if I can do something similar like you did. Appreciate the help :)

**Comment by macxcool** [comment]
The problem with what you're trying to do is that the .reg file will probably have keys for HKEY_CURRENT_USER. When you load the registry hive you do it inside another hive, like HKEY_LOCAL_MACHINE\TEMPORARY or something like that (the Invoke_HKCU... function loads it as HKEY_USERS\<SID>). If you look at the .reg file, you could copy it into a temporary folder and then fix it on the fly or you could parse the lines one at a time. It depends on the content of the .reg file which method you might use.

**Comment by macxcool** [comment]
The Get-Content loop in my example does a line-by-line parsing of the .reg file and sets up the registry settings one at a time.
Maybe a better method would be to make changes to the correct lines of the .reg file to point to the HKEY_USERS\<SID> location and then just import it. If you do that for each user profile it could work nicely.

**Comment by GamerZone360** [comment]
Again thanks for your time and support with this task. I am going to look at my options and go from there. I am actually going to test out deploying the application for user vs system context and the reg import should work has I currently have because the reg will be installed for the user who is logged in and installing the app, lol fingers cross.

I do have a dumb side note question, how do I test my toolkit package with PSEXEC? One of my Reddit post I was told to get into the habit of testing the package in PSEXEC env because you run it under system has it would when deployed via SCCM.

Thank you very much :)

**Comment by nonameneeded** [comment]
You could start the execution with psexec -s "poweshell.exe -nologo -noprofile -command <skript>"








On Tue, Sep 24, 2019 at 10:50 PM +0200, "GamerZone360" <notifications@github.com> wrote:












Again thanks for your time and support with this task. I am going to look at my options and go from there. I am actually going to test out deploying the application for user vs system context and the reg import should work has I currently have because the reg will be installed for the user who is logged in and installing the app, lol fingers cross.


I do have a dumb side note question, how do I test my toolkit package with PSEXEC? One of my Reddit post I was told to get into the habit of testing the package in PSEXEC env because you run it under system has it would when deployed via SCCM.


Thank you very much :)

**Comment by luki1412** [comment]
Invoke-HKCURegistrySettingsForAllUsers doesnt solve the issue of new users that will need the key. Thats why Active Setup exists. Also, use reg.exe instead of regedit.exe because reg.exe can run without admin permission.

**Comment by TekJunki** [comment]
Thanks for the feedback, what is this "Active Setup" you speak off? I will look into your recommendation on the reg.exe vs regedit.exe.

**Comment by ocsscott** [comment]
Is there an example for active setup with the toolkit?
________________________________

**Comment by macxcool** [comment]
@luki1412 Doesn't it? If you have it make the changes to the Default User, new user profiles will always get the changes. I like that better than Active Setup. I used AS for a long time with a large .reg file, but switched to making the changes to the Default User hive on installation. I had a lot of problems with using reg.exe and regedit.exe with AS because of certain Group Policy settings that were being applied. I found modifying the default user to be more reliable.

**Comment by powershellking** [comment]
Active Setup is the way we have used for many years. Are you planning to use it for multiple installations? If so, I'd suggest you write your own function for that purpose. This is necessary because Microsoft doesn't support Active Setup. Therefore all Active Setup registry keys are being removed during Windows 10 Feature Upgrades from version 1709 onwards. This does not mean that your settings are lost, but the keys that control the functionality of Active Setup are being deleted. So after an upgrade to a new version of Windows 10 newly created users are not getting the settings anymore. Only putting the settings in the default user would resolve the problem. But in this case only newly created users get the settings. In contrast to that Active Setup imports the settings to every user profile on logon. In addition to that with Active Setup you can do much more than just importing registry settings and you don't have to change your reg file for import. If you're fine with the restrictions regarding Active Setup in combination with Windows Feature Upgrades you could use the App deploy Toolkit function Set-ActiveSetup to create or delete Active Setup entries.

**Comment by TekJunki** [comment]
Awesome, thanks for the detailed information and this was a one-off case and I don't see myself doing it anytime soon. I am exploring other options for my issue and see if I can get it taken care of. Appreciate the help and feedback :)

**Comment by Gor3t3x** [comment]
> Awesome, thanks for the detailed information and this was a one-off case and I don't see myself doing it anytime soon. I am exploring other options for my issue and see if I can get it taken care of. Appreciate the help and feedback :)

Like powershellking said, active setup is lost between in place upgrades.

You can check free Syntaro's Active User Setup => 
There's an MSI already made : https://www.syntaro.com/modules/active-user-setup/
Or PS1 available on their GitHub : https://github.com/ThomasKur/ModernAndSecureWorkplace/tree/master/ActiveUserSetup/ActiveUserSetupSolution

**Comment by rivardma** [comment]
I am importing huge reg files with this script that I pieced together from a few more incomplete script pieces, then simply run a foreach-object and do a Set-RegistryKey
https://discourse.psappdeploytoolkit.com/t/function-to-import-reg-file/1750

**Comment by TekJunki** [comment]
Thanks all for your time and help :)

**Comment by luki1412** [comment]
> @luki1412 Doesn't it? If you have it make the changes to the Default User, new user profiles will always get the changes. I like that better than Active Setup. I used AS for a long time with a large .reg file, but switched to making the changes to the Default User hive on installation. I had a lot of problems with using reg.exe and regedit.exe with AS because of certain Group Policy settings that were being applied. I found modifying the default user to be more reliable.

Well you can use Active Setup to run any program, but Invoke-HKCURegistrySettingsForAllUsers is for registry entries only, unless you write a Run/RunOnce entry as well. Active Setup also creates entries with the same name under the User's hive when it runs so you can check whether Active setup was triggered or not. Both options have advantages and disadvantages. Other options would be using Task Scheduler or writing your own Windows Service.

**Comment by FreeWili-cloud** [comment]
```powershell
# Reg Import Users
$RegContent = Get-Content "$($adtSession.DirFiles)\Users.reg"
$InstallTemp = "C:\Temp\RegImportUsers"
Remove-ADTFolder -Path $InstallTemp
New-ADTFolder $InstallTemp

Invoke-ADTAllUsersRegistryAction  {
	$RegContent.Replace("HKEY_CURRENT_USER","HKEY_USERS\$($_.SID)") | out-file "$($InstallTemp)\$($_.SID).reg" 
	Start-ADTProcess -FilePath "regedit.exe" -ArgumentList "/s `"$($InstallTemp)\$($_.SID).reg`""
}

Remove-ADTFolder -Path $InstallTemp
```
