### ISSUE TITLE
Common Parameter may not be supported in Execute-MSI

### ISSUE THREAD

**Issue by redcrossevvy** [PSAppDeployToolkit/PSAppDeployToolkit#440]
It seems that Execute-MSI will throw an error when the -Path is null, which is okay except it displays an error prompt on the UI. I'm trying to prevent the error dialog by using common parameter -EA Stop. The problem is that the exception never makes it to my script. Is there something else that I can do to trap this dialog so it doesn't pop up on the UI? I know... test if the variable is $null, but I'm focusing on the notion that -EA may not be functioning as intended.

try {
     Execute-MSI -Action Uninstall -Path $RemoveMe[0] -ErrorAction Stop

}
catch {
     	Write-Log -Message "Error uninstalling the app. $($_.exception)" -Severity 3 -Source $deployAppScriptFriendlyName

}
![ExampleForPSADTForum_LI (2)](https://user-images.githubusercontent.com/51063997/66393308-308b8580-e9a0-11e9-9997-93a39fd5ece6.jpg)

**Comment by That-Annoying-Guy** [comment]
Execute-MSI does not have a  **-ErrorAction** parameter

NONE of the PSADT function have a **-ErrorAction** parameter

**Comment by redcrossevvy** [comment]
You will find this blurb on page 43 of the PSADT manual.
“     <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216).
“

**Comment by That-Annoying-Guy** [comment]
I rarely need the manual since I deal with the code directly. 
But I checked it out and yes, **the CommonParameters blurb is there for each function in the manual.**
I'm sorry to break it to you but I think the PSADT manual is wrong. 

There is a PowerShell feature that spits out the comments section at the top of each function **IF** the comments section is formatted properly. It seems that when they created the Functions section in the manual, they used a script that uses that feature and the **CommonParameters** section is tacked on gratuitously.  Therefore it's either a bug in that script or it's a "feature" from Microsoft.


Here is the section declaring the parameters for the Execute-MSI function (Line 2213 in AppDeployToolkitMain.ps1):

	Param (
		[Parameter(Mandatory=$false)]
		[ValidateSet('Install','Uninstall','Patch','Repair','ActiveSetup')]
		[string]$Action = 'Install',
		[Parameter(Mandatory=$true,HelpMessage='Please enter either the path to the MSI/MSP file or the ProductCode')]
		[ValidateScript({($_ -match $MSIProductCodeRegExPattern) -or ('.msi','.msp' -contains [IO.Path]::GetExtension($_))})]
		[Alias('FilePath')]
		[string]$Path,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[string]$Transform,
		[Parameter(Mandatory=$false)]
		[Alias('Arguments')]
		[ValidateNotNullorEmpty()]
		[string]$Parameters,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[string]$AddParameters,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[switch]$SecureParameters = $false,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[string]$Patch,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[string]$LoggingOptions,
		[Parameter(Mandatory=$false)]
		[Alias('LogName')]
		[string]$private:LogName,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[string]$WorkingDirectory,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[switch]$SkipMSIAlreadyInstalledCheck = $false,
		[Parameter(Mandatory=$false)]
		[switch]$IncludeUpdatesAndHotfixes = $false,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[switch]$PassThru = $false,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[boolean]$ContinueOnError = $false
	)

The authors of PSADT are really good at PowerShell but I doubt they've figured out a way to implicitly add <CommonParameters> functionality to a function without adding code. I hope they see this and update the manual.

FYI: For most PSADT functions, to mimic **-ErrorAction Stop**, use **-ContinueOnError $false** instead.

**Comment by That-Annoying-Guy** [comment]
You could try using **-Passthru** to get the exitcode and then code around that.
you also should be able to suppress popups using **-DeployMode Silent**

**Comment by DennisVH** [comment]
@redcrossevvy, the problem in your example is not that $RemoveMe[0] is null but contains 2 GUIDs: {304919FD-CB84-4697-AD26-8E2A1ECB83C4} {DEDF04B1-A8A9-4DF1-84E5-99F1A4EFCD22}.

Placing Try / Catch statement around Execute-MSI (with or without -ErrorAction Stop) avoids showing prompt on my test machine (Win10 x64 1903) when there is a parameter validation issue.
```
try {
  Execute-MSI -Action Uninstall -Path $RemoveMe[0]
}
catch { ...
```

**Comment by luki1412** [comment]
In the latest version(3.8.2+) you can stop the function from exiting the script and silence the errors so you can handle them yourself.

The common parameters are not supported in typical sense due to how they are designed. For example ErrorAction doesnt work for Throw only for Write-Error. You can't catch Write-Error, nor does it terminate the script. Its just a message in Error Stream. We would need to do a lot more to implement them in a way youre used to when using builtin cmdlets.
