### ISSUE TITLE
Adding vendor's parameters to msi installation to customize for user?

### ISSUE THREAD

**Issue by spm2600** [PSAppDeployToolkit/PSAppDeployToolkit#444]
Terribly sorry if this is remedial and noted however I'm not seeing how I can add custom parameters from a vendor to change how the install completes...

I'm using this to update clients on older versions, in addition configure properly as this wasn't done previously.

Per https://support.zoom.us/hc/en-us/articles/201362163-Mass-Installation-and-Configuration-for-Windows I'm deploying in SCCM as such: msiexec /i "ZoomInstallerFull.msi" /q ZoomAutoUpdate="true" ZNoDesktopShortCut="true" ZSSOHOST="ourdomain" ZConfig="kCmdParam_InstallOption=8;nofacebook=1"

which works just fine.

Does this require making a transform?  I'm not entirely sure how to run the msi with those features as it errors if I add directly to the  Execute-MSI command.

Additionally, and not necessarily required but ideal, I'd also like to run an executable provide in the link above which completely removes previous install, not entirely sure how to accomplish that as it requires a path.

**Comment by luki1412** [comment]
**Execute-MSI** is wrapper for msiexec so `Execute-MSI -Action Install -Path "ZoomInstallerFull.msi"` would be equivalent to `msiexec /i "ZoomInstallerFull.msi"` and the rest goes into -Parameters or of course you can use -Transform. The entire command would be:
```powershell 
Execute-MSI -Action Install -Path "ZoomInstallerFull.msi" -Parameters "/qn /norestart ZoomAutoUpdate=`"true`" ZNoDesktopShortCut=`"true`" ZSSOHOST=`"ourdomain`" ZConfig=`"kCmdParam_InstallOption=8;nofacebook=1`"" 
```

Where you use ` (backticks) to tell powershell to treat the next character as regular text, since you need doublequotes to be sent to msiexec as well and powershell uses them to know where the string starts and ends.

You can use **Execute-Process** for msi as well but that just adds more work. For exe files you need to use **Execute-Process** or **Execute-ProcessAsUser**. The syntax is almost identical. The entire documentation is inside the admin guide.docx file.

**Comment by spm2600** [comment]
Thanks for that, I had tried -Parameters but evidently didn't format properly with quotes.  Much appreciated!  I was able to sort out the executable as well.

**Comment by That-Annoying-Guy** [comment]
FYI:  Execute-MSI has 3 Parameters 

.PARAMETER Parameters
	Overrides the default parameters specified in the XML configuration file. Install default is: "REBOOT=ReallySuppress /QB!". Uninstall default is: "REBOOT=ReallySuppress /QN".
.PARAMETER AddParameters
	Adds to the default parameters specified in the XML configuration file. Install default is: "REBOOT=ReallySuppress /QB!". Uninstall default is: "REBOOT=ReallySuppress /QN".
.PARAMETER SecureParameters
	Hides all parameters passed to the MSI or MSP file from the toolkit Log file.

I ususally use **-AddParameters** so that the defaults in the XML get used and I don't end up with a massive line in the script.
