### ISSUE TITLE
Support for Intune

### ISSUE THREAD

**Issue by xsebamedox** [PSAppDeployToolkit/PSAppDeployToolkit#450]
Hi Folks,

The PsAppDeployToolkit is a great tool to deploy software with SCCM. But more and more customers want to use intune instead. Of course the PsAppDeployToolkit also works with intune. Thats not the problem. 

Problems start when thinking about a Software updates. With SCCM we always uninstalled the old version and installed the new version. In Intune we have to change that, as theres no superseedence or sth like this. 

Are there plans to optimize the PSAppDeployToolkit for Intune? For example removing the old software branding when installing an update of the same product family? Or maybe getting a chance to get access to the uninstallation method of the previous package by creating a package cache on the local devices? 

Have a nice weekend all

**Comment by luki1412** [comment]
Package cache would mean everything is on the system 3 times. 1 sccm/intune cache, 1 toolkit cache, 1 installed software. When you have packages like the ones from IBM where you have 40000 files and 8GB, this becomes a big issue. You can tell Software Centre to uninstall an app however it can be set as required so Software centre will do nothing. Not sure if it works the same way on Intune. 

So not much you can really do other than add uninstall statements in the preinstallation phase.

**Comment by That-Annoying-Guy** [comment]
In my private fork we create a custom ARP entry (ARP = Add Remove Programs, NKA Apps and Features) when we install. 
We copy all the folders except \Files\ to a local folder to support uninstall using PSADT via Apps and Features and hide the original ARP entries to help Admins always use the PSADT version to trigger a removal. 

When you trigger the uninstall, you also get a log file for the removal attempt. We merge and roll the log files too. We get one log file that contains all log files (PSADT+MSI+Setup.exe). If the admin tries to remove 5 times we get 5 log files. 

We have a function to use the locally cached files of the previous version to uninstall that looks like this:

`Remove-Package -OldPkgName $OldAppName -UseLocalUninstall	`

If the main PSADT Authors want a sanitized copy of my fork, I can make it available with some work and caveats. I'm just worried PSADT would become an animal they would not like.

**Comment by khaffner** [comment]
We don't use supersedence in sccm, so the path to Intune was easy. We script the uninstallation steps of the app (usually including earlier versions), and put it in a function. Then we call that function in the uninstallation part of Deploy-Application.ps1, and in the pre-installation step if needed. Most installers handle upgrades nicely on their own. Remove-MSIApplications is powerful here, as well as our custom Remove-ProgramsApplications. The latter is just a wrapper around Get-Package and Execute-Process.
I have not yet seen the need to modify PSADT because of Intune.

**Comment by tjgruber** [comment]
There are two ways to upgrade apps in Intune:

1. Required apps, simply replace the required app with a new required app, the new one will supersede. You'll need to ensure you have worked in your install and detection script to take care of this.

2. For non-required apps, you can use an updater app that is required but uses a requirement that app is already installed, which then is handled appropriately.

I use #2, because we have "available" apps in the company portal. Then to update them on devices, the required version of the app uninstalls and installs the new version because it's detected as already installed on the targeted device.
