### ISSUE TITLE
Show-InstallationWelcome does not detect processes where the process name param has '.exe' appended

### ISSUE THREAD

**Issue by appPackager** [PSAppDeployToolkit/PSAppDeployToolkit#46]
'''Show-InstallationWelcome -CloseApps 'notepad.exe'''' does not prompt to close my open notepad process.  The same is true for any process name with .exe appended.  

It does work in cases where I omit ".exe" from the process name: '''Show-InstallationWelcome -CloseApps 'notepad'''' 

![capture](https://cloud.githubusercontent.com/assets/12298202/8111132/9c52f31a-1025-11e5-9a75-759583be022c.PNG)

**Comment by mmashwani** [comment]
This is expected behavior. The comments for the function also make clear that this is how you should specify exe names. Part of the problem with supporting both behaviors would be you would never know if a user was specifying testapp.exe.exe or testapp.exe. It's not a very common scenario because most people name their files more logically then that but it is a possibility.

**Comment by appPackager** [comment]
Ok.  Looks like I had an old help example in my code snippet.  After looking at 3.6.4 help it appears that usage is no longer supported.
