### ISSUE TITLE
Add Functions to Add/Remove Firewall Rules

### ISSUE THREAD

**Issue by brendanmeyer** [PSAppDeployToolkit/PSAppDeployToolkit#488]
Hey

I would like to request a feature where you have internal functions (ie: with logging) that can handle Addition and Removal of Windows Firewall Rules.

I believe this would be quite useful as there are many programs out there that need additional Firewall Rules.

Regards
Brendan

**Comment by luki1412** [comment]
Hello Brendan,

that is a nice feature to have, however powershell 5.1 already has those built in.
https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule

And since Microsoft dropped support for windows 7, this doesn't really seem feasible for older versions either.

**Comment by brendanmeyer** [comment]
Hi @luki1412 

The request was more to have the New-NetFirewallRule and Remove-FirewallRule wrapped so that there is logging in the PSADT log file. As unless you do you own logging there is little or no information added to the log.

Eg: Similar to how New-Folder/Execute-Process are wrapping New-Item and Start-Process with logging.

Regards
Brendan

**Comment by luki1412** [comment]
Execute-Process isnt a wrapper for Start-Process. New-Folder is there mainly because New-Item wont create an item if the folder you want the item in, doesnt exist.

You can follow each command with Write-Log or create your own function in Extensions.ps1 however unless we add some functionality to it, there is no reason to create a copy of a function with just logging.
