### ISSUE TITLE
Execute-Process : -ExitOnProcessFailure doesn't work for all errors

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#499]
**Describe the bug**
As i understand -ExitOnProcessFailure, if $false, should allow package code to continue if Execute-Process fails. It does not for 60002 errors

**To Reproduce**
```
# Will throw 60002 because -ContinueOnError is not set to $true
Execute-Process -Path "C:\idontexist.exe"  -ExitOnProcessFailure $false
        
# Won't be executed
Write-Log -Message "test"
```

**Toolkit Version:**
3.8.2

**Comment by luki1412** [comment]
ContinueOnError is for function errors. This is function scope error. A parameter is entered but contains a nonexistent file. The process wasn't even started, therefore it couldn't fail.

**Comment by Sulquendi** [comment]
I disagree. This tool is made for being used by packagers, most of them are not lead programmers and when they are provided with an option that should not exit on process failure, then it should work as written in the manual.

**Comment by redcrossevvy** [comment]
Speaking of the manual, the version provided with 3.8.2 is labeled 3.8.1. Did the manual get updated or is it behind a revision?


On May 14, 2020, at 6:59 AM, Sulquendi <notifications@github.com> wrote:

﻿

I disagree. This tool is made for being used by packagers, most of them are not lead programmers and when they are provided with an option that should not exit on process failure, then it should work as written in the manual.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F499%23issuecomment-628557759&data=02%7C01%7Cevelyn.vose%40redcross.org%7C6a94eb499635420bcf3408d7f7f5cf18%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637250507426453825&sdata=hRyl9wWbZSgMfJKWBUptKGjwRnoU06j4l7MlMs7l4gg%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPMWRUC5CF2AFFKKTFTRRPFHJANCNFSM4NAPPABQ&data=02%7C01%7Cevelyn.vose%40redcross.org%7C6a94eb499635420bcf3408d7f7f5cf18%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637250507426453825&sdata=Iuc29SvAt37RnyyU%2FLdBFq3jrytULa3PD8tXiS%2BwkWg%3D&reserved=0>.

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by Sulquendi** [comment]
Removed my previous reply. I understand that -Exiton**Process**Failure is for the process spawned by Execute-Process and not for Execute-Process itself... I hope all packers will also get it. I don't really see the use for this addition anyway.

**Comment by luki1412** [comment]
The manual needs to be updated. The changes related to this function have been described inside changelog. It is a breaking change. ContinueOnError covers function errors now. When a process fails that is not the same as when the function fails. The previous version didnt cover function errors AT ALL, it was used for ingoring exit codes. If you need to ignore exit codes, you can just do -IgnoreExitCodes "*" and you will get the same behaviour.

So you use **ContinueOnError for function errors, ExitOnProcessFailure and IgnoreExitCodes for process errors**.

This isn't rocket science. ExitOnProcessFailure is actually very useful and was created based on a request. If you have a process that you want to run but to handle errors in your own way, you need this parameter. Without it the function Execute-Process calls Exit-Script and your code after this function will be ignored and the script ends.

**Comment by redcrossevvy** [comment]
Thanks for responding.

One of the many frustrations of working with abstracted code is trying to ferret out what code paths in the code below are doing so that you can rely on behaviors to perform in a consistent way whether those behaviors are rooted in industry standard norms or documented to occur specifically to the code below. Determining whether a behavior performs as expected is difficult when working with an abstraction. Perhaps this is a rhetorical question, but how can one determine the fine line between a process failure and a function failure in code below?..!

 I rely heavily on the manual for information and will remember now to use changelog as well.

In my attempt to debug the script and understand why setup.exe was failing, I used -IgnoreExitCodes as you suggest. I knew that 1603 was the error that I wanted to trap, but couldn’t help thinking that it would be nice to be able to wildcard and essentially trap all error codes. I missed in the documentation that the parameter accepts a wildcard and also I should have been more adventurous and have just trIed it!  :0)

Thanks for all that you do. You and the other contributors are nothing short of amazing!

On May 14, 2020, at 7:28 AM, Ultimate Luki <notifications@github.com> wrote:

﻿

The manual needs to be updated. The changes related to this function have been described inside changelog. It is a breaking change. ContinueOnError covers function errors now. When a process fails that is not the same as when the function fails. The previous version didnt cover function errors AT ALL, it was used for ingoring exit codes. If you need to ignore exit codes, you can just do -IgnoreExitCodes "*" and you will get the same behaviour.

So you use ContinueOnError for function errors, ExitOnProcessFailure and IgnoreExitCodes for process errors.

This isn't rocket science. ExitOnProcessFailure is actually very useful and was created based on a request. If you have a process that you want to run but to handle errors in your own way, you need this parameter. Without it the function Execute-Process calls Exit-Script and your code after this function will be ignored and the script ends.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F499%23issuecomment-628571386&data=02%7C01%7Cevelyn.vose%40redcross.org%7C1989efd915cf4ac030f508d7f7f9ee12%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637250525122637181&sdata=zNga8xERBJvvys492P%2F058a%2BFNnuzPIclMXVEaayRDo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPILDYGADH4ZL6LGQJLRRPIV5ANCNFSM4NAPPABQ&data=02%7C01%7Cevelyn.vose%40redcross.org%7C1989efd915cf4ac030f508d7f7f9ee12%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637250525122647186&sdata=GNaescshPx6K6K5NXPoK%2F4J7AbHmK7CQ8f891sLFku8%3D&reserved=0>.

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by luki1412** [comment]
> Thanks for responding. One of the many frustrations of working with abstracted code is trying to ferret out what code paths in the code below are doing so that you can rely on behaviors to perform in a consistent way whether those behaviors are rooted in industry standard norms or documented to occur specifically to the code below. Determining whether a behavior performs as expected is difficult when working with an abstraction. Perhaps this is a rhetorical question, but how can one determine the fine line between a process failure and a function failure in code below?..! I rely heavily on the manual for information and will remember now to use changelog as well. In my attempt to debug the script and understand why setup.exe was failing, I used -IgnoreExitCodes as you suggest. I knew that 1603 was the error that I wanted to trap, but couldn’t help thinking that it would be nice to be able to wildcard and essentially trap all error codes. I missed in the documentation that the parameter accepts a wildcard and also I should have been more adventurous and have just trIed it! :0) Thanks for all that you do. You and the other contributors are nothing short of amazing! On May 14, 2020, at 7:28 AM, Ultimate Luki <notifications@github.com> wrote: ﻿ The manual needs to be updated. The changes related to this function have been described inside changelog. It is a breaking change. ContinueOnError covers function errors now. When a process fails that is not the same as when the function fails. The previous version didnt cover function errors AT ALL, it was used for ingoring exit codes. If you need to ignore exit codes, you can just do -IgnoreExitCodes "*" and you will get the same behaviour. So you use ContinueOnError for function errors, ExitOnProcessFailure and IgnoreExitCodes for process errors. This isn't rocket science. ExitOnProcessFailure is actually very useful and was created based on a request. If you have a process that you want to run but to handle errors in your own way, you need this parameter. Without it the function Execute-Process calls Exit-Script and your code after this function will be ignored and the script ends. — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F499%23issuecomment-628571386&data=02%7C01%7Cevelyn.vose%40redcross.org%7C1989efd915cf4ac030f508d7f7f9ee12%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637250525122637181&sdata=zNga8xERBJvvys492P%2F058a%2BFNnuzPIclMXVEaayRDo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPILDYGADH4ZL6LGQJLRRPIV5ANCNFSM4NAPPABQ&data=02%7C01%7Cevelyn.vose%40redcross.org%7C1989efd915cf4ac030f508d7f7f9ee12%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637250525122647186&sdata=GNaescshPx6K6K5NXPoK%2F4J7AbHmK7CQ8f891sLFku8%3D&reserved=0>. CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

IgnoreExitCodes used to only work with specified exit codes but now you can use "*" to ignore all of them. I didnt put the star in there as a placeholder, it is now supported. When it comes to the documentation, we need to work on that. The descriptions of the functions that are inside the script are modifed when the script is changed, however the document isn't. Document gets a changed before the release and we sometimes forget to do that. I apologize for this. You can see the Help.ps1 for now for documentation. You can just call it and wait a bit, it will display a window with functions and descriptions for them, taken from the script directly.
