### ISSUE TITLE
Question on "Write-Log"-Update regarding "Source"-Parameter

### ISSUE THREAD

**Issue by NordicAT** [PSAppDeployToolkit/PSAppDeployToolkit#503]
Hello,

I just tested the latest 3.8.2 PSADTK-Version coming from 3.8.0.

I make extensively usage of "**Write-Log**" in all my packages and there seems to be a change in the function:

Command:
`Write-Log -Message "$appVendor $appName (Version: $appVersion) is beeing installed ..." -Severity 1`

Output-Before:
> [05-17-2020 12:20:49.124] [Installation] :: VideoLAN VLCPlayer (Version: 3.0.10) is beeing installed ...

Output-After:
> [05-17-2020 12:19:25.723] [Installation] [Unknown] :: VideoLAN VLC Player (Version: 3.0.10) is beeing installed ...

---

Of course this is only a cosmetical issue, but now the logs are full of **[Unknown]** -strings.

The changelog of 3.8.1 says:
> Added default -Source parameter value for Write-Log to fix CMTrace not displaying severity

The word-manual says for the source-parameter:

> -Source <String>
> The source of the message being logged.

---

I am sorry, but I am still not sure, what the parameter "Source" is meant for?

What should I use for the source to get rid of [unknown]? (Recommendation)
Ideally the log-line should look like before.

Thank you

**Comment by luki1412** [comment]
This parameter is used for the Source of the log entry. What is the origin of this log entry.
If the Source is missing, CMTrace doesn't display the entry as red or yellow for errors and warnings.
So if you omit this parameter, a value of Unknown is used so its not empty and the log is displayed correctly. You usually want to put the name of the function there.

**Comment by redcrossevvy** [comment]
Would it be possible, perhaps as a feature request, to default this to $appName, to reduce redundant typing?


On May 17, 2020, at 8:45 AM, Ultimate Luki <notifications@github.com> wrote:

﻿

This parameter is used for the Source of the log entry. What is the origin of this log entry.
If the Source is missing, CMTrace doesn't display the entry as red or yellow for errors and warnings.
So if you omit this parameter, a value of Unknown is used so its not empty and the log is displayed correctly. You usually want to put the name of the function there.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F503%23issuecomment-629791151&data=02%7C01%7Cevelyn.vose%40redcross.org%7Cf73b7af2c79b4513afd808d7fa603d32%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637253163577046816&sdata=KB38yr0LiyXgbL5WHmjuMPHo0alXu2MNHwbfnXNgdTo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPIYPSL73R4KIKHPQDDRR7MADANCNFSM4NDKKQFA&data=02%7C01%7Cevelyn.vose%40redcross.org%7Cf73b7af2c79b4513afd808d7fa603d32%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637253163577056769&sdata=IY82RpV6rrrl2h10Z%2FzjYuosDxOYz5Fhb%2Bu2UUh27Ek%3D&reserved=0>.

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by NordicAT** [comment]
@luki1412 : Thank you for the explanation.

> You usually want to put the name of the function there.

I already saw, that it is used for the function name.
But I use "Write-Log" in the main-script (Deploy-Application.ps1) and not inside a function.
I am unsure about what to name it.

> Would it be possible, perhaps as a feature request, to default this to $appName, to reduce redundant typing?

I think this would not be a good idea either. 
If I use Write-Log without source-parameter in the main script, "$appName" would be used.
Everywhere else in the toolkit it uses the function-name without $appName. This is somehow inconsistent.

**Comment by luki1412** [comment]
It wouldn't be a problem at all. We just need to decide on the best default value.

**Comment by NordicAT** [comment]
Please find below some suggestions:

- Main
> [05-17-2020 12:19:25.723] [Installation] **[Main]** :: Installing App ...

- Main-Script
> [05-17-2020 12:19:25.723] [Installation] **[Main-Script]** :: Installing App ...

- Deploy-Application
> [05-17-2020 12:19:25.723] [Installation] **[Deploy-Application]** :: Installing App ...

- AppDeploy
> [05-17-2020 12:19:25.723] [Installation] **[AppDeploy]** :: Installing App ...

- deployAppScript
> [05-17-2020 12:19:25.723] [Installation] **[deployAppScript]** :: Installing App ...

- appScript
> [05-17-2020 12:19:25.723] [Installation] **[appScript]** :: Installing App ...

**Comment by redcrossevvy** [comment]
My vote remains for $appName. Keep it simple...


On May 17, 2020, at 12:58 PM, NordicAT <notifications@github.com> wrote:

﻿

Please find below some suggestions:

  *   Main

[05-17-2020 12:19:25.723] [Installation] [Main] :: Installing App ...

  *   Main-Script

[05-17-2020 12:19:25.723] [Installation] [Main-Script] :: Installing App ...

  *   Deploy-Application

[05-17-2020 12:19:25.723] [Installation] [Deploy-Application] :: Installing App ...

  *   AppDeploy

[05-17-2020 12:19:25.723] [Installation] [AppDeploy] :: Installing App ...

  *   deployAppScript

[05-17-2020 12:19:25.723] [Installation] [deployAppScript] :: Installing App ...

  *   appScript

[05-17-2020 12:19:25.723] [Installation] [appScript] :: Installing App ...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F503%23issuecomment-629828438&data=02%7C01%7Cevelyn.vose%40redcross.org%7C578dac8d032b451b622308d7fa838369%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637253315071825045&sdata=kIiAeq0LoCdDeiji2OjIu8Kav0qw4jSD4FkLShMkaio%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPJ2CRKCKGF3RN4N4A3RSAJS7ANCNFSM4NDKKQFA&data=02%7C01%7Cevelyn.vose%40redcross.org%7C578dac8d032b451b622308d7fa838369%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637253315071825045&sdata=rgBnOWVS30x2k7%2BPcff6HeozuuDDqlwH34Xk8NUB%2BqE%3D&reserved=0>.

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by redcrossevvy** [comment]
Or installation phase if you’d like to see what section of the script template is executing.


﻿ My vote remains for $appName. Keep it simple...


On May 17, 2020, at 12:58 PM, NordicAT <notifications@github.com> wrote:

﻿

Please find below some suggestions:

  *   Main

[05-17-2020 12:19:25.723] [Installation] [Main] :: Installing App ...

  *   Main-Script

[05-17-2020 12:19:25.723] [Installation] [Main-Script] :: Installing App ...

  *   Deploy-Application

[05-17-2020 12:19:25.723] [Installation] [Deploy-Application] :: Installing App ...

  *   AppDeploy

[05-17-2020 12:19:25.723] [Installation] [AppDeploy] :: Installing App ...

  *   deployAppScript

[05-17-2020 12:19:25.723] [Installation] [deployAppScript] :: Installing App ...

  *   appScript

[05-17-2020 12:19:25.723] [Installation] [appScript] :: Installing App ...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F503%23issuecomment-629828438&data=02%7C01%7Cevelyn.vose%40redcross.org%7C578dac8d032b451b622308d7fa838369%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637253315071825045&sdata=kIiAeq0LoCdDeiji2OjIu8Kav0qw4jSD4FkLShMkaio%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPJ2CRKCKGF3RN4N4A3RSAJS7ANCNFSM4NDKKQFA&data=02%7C01%7Cevelyn.vose%40redcross.org%7C578dac8d032b451b622308d7fa838369%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637253315071825045&sdata=rgBnOWVS30x2k7%2BPcff6HeozuuDDqlwH34Xk8NUB%2BqE%3D&reserved=0>.

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by luki1412** [comment]
In CMTrace -Source is used as Component and in legacy logging it is specified after script section.
We can't call it Main or Main script because we already have a main script - Main.ps1 so that would be confusing. I think the best option here would be Deploy-Application or whatever the name of this script file is, because it can be changed.

**Comment by NordicAT** [comment]
Hello,

> Or installation phase if you’d like to see what section of the script template is executing.

But if you would use the installation phase, then it would look like this, or not?

> [05-17-2020 12:19:25.723] [Installation] **[Installation]** :: Installing App ...

- - - 

> My vote remains for $appName. Keep it simple...

When Write-Log is beeing called from a function, then the function-name is used. Wouldn't it look inconsistent, when there $appName is beeing used in between? Example:

> [05-17-2020 12:19:25.723] [Installation] **[Execute-Process]** :: Do something ...
> [05-17-2020 12:19:25.723] [Installation] **[VLC Player]** :: Do something ...
> [05-17-2020 12:19:25.723] [Installation] **[Show-BalloonTip]** :: Do something ...

**Comment by NordicAT** [comment]
@luki1412 :

> I think the best option here would be Deploy-Application or whatever the name of this script file is, because it can be changed.

I think using `$MyInvocation.MyCommand.Name`, which resolves to "**Deploy-Application.ps1**", pre-defined as default-name would be OK for me too.

Please find visualized examples below:

**Console-Log - Before:**
![Console-Before](https://user-images.githubusercontent.com/42859522/82190276-19772380-98f1-11ea-81af-91046e311372.png)

**Console-Log - After:**
![Console-After](https://user-images.githubusercontent.com/42859522/82190275-18de8d00-98f1-11ea-993c-ba21f595ce9b.png)

- - -

**CMTrace - Before:**
![CMTrace-Before](https://user-images.githubusercontent.com/42859522/82190273-1845f680-98f1-11ea-94c4-e00c30482360.png)

**CMTrace - After:**
![CMTrace-After](https://user-images.githubusercontent.com/42859522/82190271-1714c980-98f1-11ea-9f5a-b31e2aaeb1f5.png)

**Comment by luki1412** [comment]
Im going to use a more elegant solution. It will get the parents name function and if not in a function then the name of the script. If not called from a script or a function then 'Unknown' will be used.

**Comment by NordicAT** [comment]
Sounds good - Thank you!

**Comment by Sulquendi** [comment]
About Write-Log and the -source parameter, a suggestion : instead of using -Source ${CmdletName} at every calls to this function (and declaring `[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name` in every Begin blocks of the template functions), you could remove it globally and use [string]$Source = `$(Get-PsCallStack)[0].FunctionName` in Write-Log; with this modifier in the begin of Write-Log : 
` $source =  $source -replace '<.*>$', ''
		if ([string]::IsNullOrEmpty($source)) { $source = 'unknown-or-whatever' }`

After that, -source is in auto-pilot mode.

Regards
