### ISSUE TITLE
Show-InstallationPrompt shows during Silent install

### ISSUE THREAD

**Issue by ChThomas** [PSAppDeployToolkit/PSAppDeployToolkit#52]
Does anyone else have the Show-InstallationPrompt from POST-INSTALLATION display even during a Silent install? I was running into that and I want one source folder with multiple deployment types for Silent or not. My workaround was to put an If statement into the section. If others are noticing this, could you consider building the if statement into the default script?

```
If (-not $useDefaultMsi) {
    If ($DeployMode -ne "Silent") {
        # Inform the user that the installation has completed
        Show-InstallationPrompt -Message "$installTitle has completed installation. `n `n If you encounter any issues with this software please enter a ticket or call Help Desk at x4357." -Icon "Information" -ButtonMiddleText "OK" -NoWait
    }
}
```

**Comment by replicaJunction** [comment]
I've noticed this behavior for a long time - since at least the 3.1 release (that was about when I started using this toolkit).  Personally, I agree that a "silent" install shouldn't display an installation prompt like this.  We should also account for NonInteractive deploy mode, so I'd suggest something like this instead for Deploy-Application.ps1:

```powershell
If (-not $useDefaultMsi) {
    If ($DeployMode -eq 'Interactive') {
        ## Display a message at the end of the install
        Show-InstallationPrompt -Message 'You can customize text to appear at the end of an install or remove it completely for unattended installations.' -ButtonRightText 'OK' -Icon Information -NoWait
    }
}
```

I'd be happy to submit a pull request for this if you all would like. :)

**Comment by seanlillis** [comment]
Agreed, this is now corrected to work consistently for Show-InstallationPrompt and Show-InstallationRestartPrompt in line with the documentation.
