### ISSUE TITLE
Encrypt a password in a psappdeploy script

### ISSUE THREAD

**Issue by aurelgodin** [PSAppDeployToolkit/PSAppDeployToolkit#521]
Hello,

I must prepare a kaspersky Endpoint 11 package, for the uninstallation I must indicate the login and password for the uninstallation of kaspersky in the psappdeploy code.

I wanted to know if it was possible to encrypt the login and password or only the password so as not to have the information in plain text in the psappdeploy code?

**Comment by luki1412** [comment]
Hello,

the problem with this is that in order to encrypt something you will have to be able to decrypt it which means you would have to include the key, defeating the purpose of encrypting it in the first place. So you either have to have the key already on the machine or you will have to send it prior to the script. 

The toolkit currently doesn't supply a function for encryption/decryption.

**Comment by aurelgodin** [comment]
Thanks for your feedback.
In this case it is possible to hide the login and password in the logs from psappdeploy

**Comment by psour** [comment]
Yes it is possible to hide Parameters from log use -secureparameters switch for execute-process, Execute-ProcessAsUser or execute-msi.
Also You can use ConvertFrom/To-Secure String with KEY File and NTFS Permission Protection. But in the end you will need and provide a clear text password to an executable. But for the record, this is possible.
