### ISSUE TITLE
Execute-Process Exit Code Question

### ISSUE THREAD

**Issue by TekJunki** [PSAppDeployToolkit/PSAppDeployToolkit#527]
**My Question/Issue:**
Packaging up application (Dell Command Update) and the Execute-Process is failing with exit code [1]. After looking at the Dell Guide, exit code one is just telling to reboot the system since its being suppressed in the install process. The question is how can I turn that exit code into a success code?

**What I have tried so far:**
I have googled the issue and haven't found what I am looking for. I also looked into the Admin Guide and didn't find any info related to my question. I did however find the following $ExecuteResult.ExitCode

**Screenshots or additional details:**
`## Display a message at the end of the install
If (-not $useDefaultMsi) {

## Reboot System After POST-INSTALLATION Process Completes
If ($ExecuteResult.ExitCode -eq 1) {
Show-InstallationRestartPrompt -Countdownseconds 60 -CountdownNoHideSeconds 60
}
ElseIf ($mainExitCode -eq 0) {
Show-InstallationPrompt -Message "The Dell Command Update Tool has scanned your system and applied the correct updates. For the changes to take into effect, please restart your system, thank you."  -ButtonRightText 'OK' -Icon Information -NoWait
}
}
}
ElseIf ($deploymentType -ieq 'Uninstall') {`

Thank you for your time and help.

**Comment by redcrossevvy** [comment]
You could consider -PassThru and examine the exit code yourself or use -IgnoreExitCode ‘1’

You’ll need v3.8 for the latter.

On Jul 1, 2020, at 6:29 PM, TekJunki <notifications@github.com> wrote:

﻿

My Question/Issue:
Packaging up application (Dell Command Update) and the Execute-Process is failing with exit code [1]. After looking at the Dell Guide, exit code one is just telling to reboot the system since its being suppressed in the install process. The question is how can I turn that exit code into a success code?

What I have tried so far:
I have googled the issue and haven't found what I am looking for. I also looked into the Admin Guide and didn't find any info related to my question. I did however find the following $ExecuteResult.ExitCode

Screenshots or additional details:
`## Display a message at the end of the install
If (-not $useDefaultMsi) {

Reboot System After POST-INSTALLATION Process Completes

If ($ExecuteResult.ExitCode -eq 1) {
Show-InstallationRestartPrompt -Countdownseconds 60 -CountdownNoHideSeconds 60
}
ElseIf ($mainExitCode -eq 0) {
Show-InstallationPrompt -Message "The Dell Command Update Tool has scanned your system and applied the correct updates. For the changes to take into effect, please restart your system, thank you." -ButtonRightText 'OK' -Icon Information -NoWait
}
}
}
ElseIf ($deploymentType -ieq 'Uninstall') {`

Thank you for your time and help.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F527&data=02%7C01%7Cevelyn.vose%40redcross.org%7C177a811f5eff4023bd2808d81e0e2718%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C1%7C637292393420714938&sdata=v%2BPbKEGy28ACb%2BJKRjgLK9kp59qKMX%2FIZsuLU4ptu%2Bc%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPNSXN4LGPWWRMQ5ZRTRZO2CXANCNFSM4OOEMDZQ&data=02%7C01%7Cevelyn.vose%40redcross.org%7C177a811f5eff4023bd2808d81e0e2718%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C1%7C637292393420724932&sdata=6XvBSqb2LTaOioEDhdGuIZ0RrGXcx4R5h%2Bl1lIo%2BbwE%3D&reserved=0>.

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by TekJunki** [comment]
> You could consider -PassThru and examine the exit code yourself or use -IgnoreExitCode ‘1’ You’ll need v3.8 for the latter.

Thanks for the feedback and I am actually using the -IgnoreExitCode in my code (see below). When running with this option, I am getting the following feedback in the logs "Execute-Process:: Execution completed and the exit code [1] is being ignored "

Can you explain to me for my learning knowledge that when we ignore an exit code, what does it actually means? My guess is that you are just telling the PSADTK to just ignore the exit code and it will report to SCCM as Successful Install, correct?

`		
## Perform Full System Scan To Check For Dell Updates
Show-InstallationProgress -StatusMessage "Scanning System For Dell Updates" 
Execute-Process -Path $DCUCLI -Parameters $Scan -CreateNoWindow -IgnoreExitCodes '2,500'
		
## Apply Dell Updates To System
Show-InstallationProgress -StatusMessage "Applying Latest Dell Updates" 
Execute-Process -Path $DCUCLI -Parameters $Apply -CreateNoWindow -IgnoreExitCodes '2,500'`

**Comment by luki1412** [comment]
> > You could consider -PassThru and examine the exit code yourself or use -IgnoreExitCode ‘1’ You’ll need v3.8 for the latter.
> 
> Thanks for the feedback and I am actually using the -IgnoreExitCode in my code (see below). When running with this option, I am getting the following feedback in the logs "Execute-Process:: Execution completed and the exit code [1] is being ignored "
> 
> Can you explain to me for my learning knowledge that when we ignore an exit code, what does it actually means? My guess is that you are just telling the PSADTK to just ignore the exit code and it will report to SCCM as Successful Install, correct?
> 
> `
> 
> ## Perform Full System Scan To Check For Dell Updates
> Show-InstallationProgress -StatusMessage "Scanning System For Dell Updates"
> Execute-Process -Path $DCUCLI -Parameters $Scan -CreateNoWindow -IgnoreExitCodes '2,500'
> 
> ## Apply Dell Updates To System
> Show-InstallationProgress -StatusMessage "Applying Latest Dell Updates"
> Execute-Process -Path $DCUCLI -Parameters $Apply -CreateNoWindow -IgnoreExitCodes '2,500'`

Ignoring exit codes means that it will be treated as if the process returned 0.
