### ISSUE TITLE
Show-InstallationWelcome buttons

### ISSUE THREAD

**Issue by quoc77** [PSAppDeployToolkit/PSAppDeployToolkit#55]
I like to make a request to update the Show-InstallationWelcome window.  When there are running applications that needs to be close with deferment options, users see three buttons (Close Program, Defer, and Continue)  Many of my users expect that when they hit Continue that it would close the program out for them, but it doesn't.  So my request is that when no programs needs to be close, the only two buttons a users see is Defer and Continue.  If there are running processes that needs to be close, the only button display is Close Program and Defer.

Thank you,
Living with difficult users

**Comment by mmashwani** [comment]
The "Continue" button is there so that users can save their work in their apps, close them, and then hit "Continue". What version of the toolkit are you using? The latest version now has a tooltip that pops up as soon as you hover the mouse over the "Continue" button that explain exactly what the button does and when it should be used. Let me know if the tooltip in the latest version solves your problem.

**Comment by quoc77** [comment]
I'm using 3.6.4, and I don't see a tool-tip pop-up when the mouse is over the Continue button.

**Comment by mmashwani** [comment]
The tooltip was added in 3.6.3. Can you share one of the language sections from your config XML file?

**Comment by quoc77** [comment]
I see it the tooltip now.  Thank you!
