### ISSUE TITLE
Remove-File treats already deleted (or mising files) as errors

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#57]
If you use Remove-File to delete a file that does not exists, Remove-File treats the situation as an error:

	[07-07-2015 13:03:09.789] [Pre-Uninstallation] [Remove-File] :: Delete file in path [C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Client 6.0\Client 6.0.lnk]...
	[07-07-2015 13:03:09.805] [Pre-Uninstallation] [Remove-File] :: Failed to delete file(s) in path [C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Client 6.0\Client 6.0.lnk].
	Error Record:
	-------------

	Message        : Cannot find path 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Client 6.0\Client 6.0.lnk' because it does not exist.
	InnerException :

	FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

	PositionMessage :
					  At \\blabla\share\Client_v6r3\AppDeployToolkit\AppDeployToolkitMain.ps1:2955
					  char:16
					  +                 Remove-Item <<<<  -Path $path -Force -ErrorAction 'Stop' | Out-Null

Granted, it does continue on but I'm worried that QA and other techs will see this as "a bad thing" and will call me to ask if it's OK or not.

Can this be suppressed if Remove-File has no file to delete?

**Comment by mmashwani** [comment]
Well I would want some indication that the file I wanted to delete does not exist. Instead of an error, I could mark that log entry as a warning instead but that doesn't make as much sense to me. Also, that log entry will catch errors other than the file not existing. I would rather avoid adding multiple catches for different error types just so that the log entry is not highlighted as red for the file not existing.

I think the easier solution on your end would be to use Test-Path to test if a files exists before trying to delete it.

**Comment by That-Annoying-Guy** [comment]
I agree.
Even before I submitted the "issue" I looked at the code and I could not suggest anything because it was so elegantly simple.

Test-path in deploy-Application.ps1 is it.
