### ISSUE TITLE
Show-InstallationProgress Functionality

### ISSUE THREAD

**Issue by PaulAndrewsYEG** [PSAppDeployToolkit/PSAppDeployToolkit#610]
We are moving our default template from 3.8.2 to 3.8.4 and something has changed in how Show-InstallationProgress functions. In the past when you launched this function the windowlocation was TopCenter, but since 3.8.3 the default location is in now dead center of the screen. 

If you use the -WindowLocation TopCenter parameter it observes the previous default behaviour. The function parameter information even states the default is top centers.

.PARAMETER WindowLocation
	The location of the progress window. Default: just below top, centered.

Is center of screen supposed to be the new behaviour, if not is there an easy fix to ensure top center is observed as default.I would assume the behaviour should be topcenter (default), bottomright  and center should be the options, but I could be wrong.

Any assistance is greatly appreciated.

**Comment by luki1412** [comment]
The parameter description is incorrect. Is it centered now. This function is the only using WPF for the window and centering it has its issue. Previously, the DPI was not taken into consideration and ended up not being centered. That has been reworked. We decided to change the default location to the center because all other windows are in the center. Use -WindowLocation TopCenter. I will add a PR that fixes the incorrect parameter description.
