### ISSUE TITLE
Seeking help to bypass installation exit codes other than 0.

### ISSUE THREAD

**Issue by bm109591** [PSAppDeployToolkit/PSAppDeployToolkit#64]
Hi Team,

Need your help to avoid installation failed balloon message for Installation exit code 129.

![exitcode129](https://cloud.githubusercontent.com/assets/12154193/8754272/f8f134e8-2cdf-11e5-91e8-92783f8f6593.JPG)

Please help me with syntax for avoiding exit code as an error for following execution

Execute-Process -Path 'SAPGUI740_20150521_1557.exe' -Parameters '/Silent'
Wait-Process -Name SAPGUI740_20150521_1557

Thank you!

Regards,
Bala

**Comment by mmashwani** [comment]
Have you looked at all of the parameters for Execute-Process? There is a parameter called -IgnoreExitCodes that does exactly what you're asking. There is also an example that shows the use of this parameter.

**Comment by bm109591** [comment]
Thank you so much Mashwani for prompt reply :)

**Comment by Shweta-Jagyasi** [comment]
-IgnoreExitCodes does not worked. So tried : Execute-Process -ContinueOnError $True -Path -ContinueOnError worked.

**Comment by redcrossevvy** [comment]
You didn’t mention it, but I’m wondering what arguments you may have used? I’ve had good luck with -IgnoreExitCodes “*” and also -IgnoreExitCodes “1603”. Was there one that didn’t work for you?

On Jun 9, 2020, at 7:24 AM, Shweta-Jagyasi <notifications@github.com> wrote:

﻿

-IgnoreExitCodes does not worked. So tried : Execute-Process -ContinueOnError $True -Path -ContinueOnError worked.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F64%23issuecomment-641226905&data=02%7C01%7Cevelyn.vose%40redcross.org%7Cc75f9aa35ea345c3f5a708d80c67a83b%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637272986627183627&sdata=ifN8BgkMuMWy%2Ffw0oztblZVnXUGy%2Bbc1HjcTzmIL%2FF4%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPMCYLE6GYBUBNF4KH3RVYLWJANCNFSM4BLLRNYA&data=02%7C01%7Cevelyn.vose%40redcross.org%7Cc75f9aa35ea345c3f5a708d80c67a83b%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637272986627183627&sdata=Mhf2eu2r28xuOWB7FMZMGLoZ0brUAy3vIv31nTBnTT8%3D&reserved=0>.

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
