### ISSUE TITLE
Logging for non PSADT commands

### ISSUE THREAD

**Issue by pilgi3** [PSAppDeployToolkit/PSAppDeployToolkit#654]
**My Question/Issue:**
Is it possible to log standard command in the logfile?
For example "expand-archive".

**What I have tried so far:**
Using the syntax of Execute-ProcessAsUser with Execute-Process.

**Screenshots or additional details:**
I am using the Expand-Archive command in the Install section.
![image](https://user-images.githubusercontent.com/44865075/118632817-16976300-b7d1-11eb-97ec-a14ee90d13fb.png)

**Comment by That-Annoying-Guy** [comment]
This is something that should be mentioned in the PSADT manual.
Most people don't care about this until they have fingers pointing at them or get fired for being careless.

For example, logging is the main reason to use PSADT's Copy-File instead of the built-in Copy-Item. You are not going to be told in the log files why Copy-Item failed unless you are really know what you are doing.

I use these 2 methods:
**1. Redirection**
This the a quick and dirty method that I use when I can:

	Remove-NetFirewallRule -DisplayName $RuleName -Verbose *>&1 | Out-String | write-log

I use the -Verbose switch to make sure Write-log has something to write. Otherwise Write-log will blow up and take to the whole install with it.
It works most times but some fancy cmdlets still don't report errors like Set-Service. So..

**2. Cmdlet variables**

This is my latest bulletproof way to force logging out of cmdlets:

	$OutputText = Set-Service -Name AdobeARMservice -Verbose -StartupType Disabled -ErrorVariable ErrVar -OutVariable OutVar -WarningVariable WarnVar -ErrorAction SilentlyContinue | Out-String
	Write-Log "[$OutputText] [$ErrVar] [$OutVar] [$WarnVar]"
	Remove-variable ErrVar,OutVar,WarnVar -ErrorAction SilentlyContinue
	
The only thing you will want to watch-out for is the -ErrorAction switch. Make sure to set it to STOP to make Try/Catch work.

**Comment by pilgi3** [comment]
Ok,I know that's not a bug.
So I select the template 'Question'.

![image](https://user-images.githubusercontent.com/44865075/121073793-4a174d00-c7d3-11eb-9175-e5ab4fb83dcd.jpeg)

![image](https://user-images.githubusercontent.com/44865075/121073832-569ba580-c7d3-11eb-8ceb-67226f95308d.jpeg)

**Comment by That-Annoying-Guy** [comment]
I use these 2 methods:
**1. Redirection**
This the a quick and dirty method that I use when I can:

	Remove-NetFirewallRule -DisplayName $RuleName -Verbose *>&1 | Out-String | write-log

I use the -Verbose switch to make sure Write-log has something to write. Otherwise Write-log will blow up and take to the whole install with it.
It works most times but some fancy cmdlets still don't report errors like Set-Service. So..

**2. Cmdlet variables**

This is my latest bulletproof way to force logging out of cmdlets:

	$OutputText = Set-Service -Name AdobeARMservice -Verbose -StartupType Disabled -ErrorVariable ErrVar -OutVariable OutVar -WarningVariable WarnVar -ErrorAction SilentlyContinue | Out-String
	Write-Log "[$OutputText] [$ErrVar] [$OutVar] [$WarnVar]"
	Remove-variable ErrVar,OutVar,WarnVar -ErrorAction SilentlyContinue
	
The only thing you will want to watch-out for is the -ErrorAction switch. Make sure to set it to STOP to make Try/Catch work.

**Comment by pilgi3** [comment]
Thanks!
I tested both methods.
Method 1 works.
With Method 2 I get this output:

![grafik](https://user-images.githubusercontent.com/44865075/121857969-6bf26180-ccf6-11eb-8e91-c25132060511.png)

My cmdlines are:
`$OutputText = Expand-Archive -Path "$dirFiles\openjdk-16.0.1_windows-x64_bin.zip" -DestinationPath "$env:ProgramFiles\OpenJDK" -Force -Verbose -ErrorVariable ErrVar -OutVariable OutVar -WarningVariable WarnVar -ErrorAction SilentlyContinue | Out-String

Write-Log "[$OutputText] [$ErrVar] [$OutVar] [$WarnVar]"
Remove-Variable ErrVar,OutVar,WarnVar -ErrorAction SilentlyContinue`

**Comment by That-Annoying-Guy** [comment]
If no errors occurred and the ZIP file extracted OK, it may be that **Expand-Archive** is not very talkative.
Maybe changing **SilentlyContinue** to **Continue** will give you confirmation of success.
You could do a **test-path** on the last file is extracts for Proof of life.
I haven't needed to use **Expand-Archive** yet so I can't help you much.

**Comment by pilgi3** [comment]
In my scenario method 1 is OK.
Thank your for your help!
