### ISSUE TITLE
Use Functions from AppDeployToolkitMain.ps1 inside of AppDeployToolkitExtensions.ps1

### ISSUE THREAD

**Issue by MarcoGriep88** [PSAppDeployToolkit/PSAppDeployToolkit#698]
**My Question/Issue:**
I want to extend the ADT and insert some custom logic inside of AppDeployToolkitExtensions.ps1 and access functions that are inside Main.ps1. 

**What I have tried so far:**
I can use my cmdlet from the Extensions file inside of App-Deployment.ps1 like expected, but when I use Get-HardwarePlatform inside of Extensions.ps1 "Get-HardwarePlatform" is unknown and I get an exception. How can I access those functions inside Main.ps1. Thanks

**Comment by That-Annoying-Guy** [comment]
That's because the AppDeployToolkitExtensions.ps1 script does not load the functions from AppDeployToolkitMain.ps1

Build your new functions in a **App-Deployment.ps1** file.
Once they work, move them to the AppDeployToolkitExtensions.ps1 file.

That way when you launch **App-Deployment.ps1**, **App-Deployment.ps1** will load the functions in AppDeployToolkitMain.ps1 and AppDeployToolkitExtensions.ps1 files and then all the functions will work in **App-Deployment.ps1**

**Comment by mjr4077au** [comment]
This stuff is addressed in v4 by way of a module-based backend. Extensions would be written as your own modules to build on top of ours.
