### ISSUE TITLE
Block-Execution and NonInteractive

### ISSUE THREAD

**Issue by narabug** [PSAppDeployToolkit/PSAppDeployToolkit#699]
It’s a bit awkward to have the hidden check for NonInteractive installs for the Block-Execution function.

Presumably if I am blocking the execution of an application, that means that re-launching it will break the installation, and whether that install is silent or interactive has no bearing on that breaking action.

**Comment by denisrennes** [comment]
Yes it's true, during a NonInteractive installation the Block-AppExecution function does nothing, this is surprising and undocumented.

**Comment by seanlillis** [comment]
@mmashwani I believe the rationale for disabling the Block-AppExecution function during a non-interactive install was to avoid using this feature unnecessarily, due to the risk of failures in unblocking the app, which might have been an issue in early versions. This decision was based on the assumption that it would only be a user triggering launching of the blocked apps. Since there can also be other scenarios, I've removed this logic from the Block-AppExecution and Unblock-AppExecution functions in the latest commit.

**Comment by seanlillis** [comment]
This will be changed in the next release, thank you.

**Comment by seanlillis** [comment]
Fixed in v3.9.0.
