### ISSUE TITLE
SCCM Permissions Issue - Non-Admin User

### ISSUE THREAD

**Issue by SchneiderNick** [PSAppDeployToolkit/PSAppDeployToolkit#705]
**Describe the bug**
When trying to run a script to interact with Outlook through an SCCM deployment, we are running into an issue where we cannot push the script to users that are not admins on their machines. When run from SCCM as a deployment on an Admin's machine, the script runs perfectly fine; however, when run on any other users device, there is an issue with permissions that pops up. 

**To Reproduce**

Run script on Admin computer using SCCM - Works
Run script on Non-Admin Computer with SCCM - Doesn't work

**Screenshots**
![image](https://user-images.githubusercontent.com/53909583/161063177-e916eaa9-f990-4b12-85e1-3858ed379967.png)

**Toolkit Version:**
3.8.4

**Powershell Version:**
5.1.19041.1320

**Additional context**
The script additions are wirtten to search through the users computer and discover/move any PST files they have mounted or stored.

**Comment by That-Annoying-Guy** [comment]
Please note that this section is for PSADT bugs and feature requests. 
Your issue is a SCCM deploy issue. 
This should have been posted in https://discourse.psappdeploytoolkit.com/c/thetoolkit/general-discussion

https://www.reddit.com/r/SCCM/comments/89i72r/deploying_applications_to_users_with_no_admin/

This issue should be closed in about a week.

**Comment by WebBuddha** [comment]
Did you changed the Param <Toolkit_RequireAdmin>False</Toolkit_RequireAdmin> in the AppDeployToolitConfig.xml already?
SCCM installations to non-admin Clients are working fine on my side.

**Comment by seanlillis** [comment]
Question relates to SCCM configuration.
