### ISSUE TITLE
Show-InstallationWelcome Prompt Not Appearing over the Company Portal

### ISSUE THREAD

**Issue by Iboo1995** [PSAppDeployToolkit/PSAppDeployToolkit#709]
Hey, 

I am currently trying to show the Show-InstallationWelcome Prompt over Intune (Company Portal).
If I run the Process locally on a Windows 10 Client (CMD) it is appearing correctly (The Window Appears and give the User the ability to Close the Application).
![Show-Prompt](https://user-images.githubusercontent.com/61466187/162950142-7972078c-1764-4ed4-ad23-9372a3814f14.png)

Nevertheless, the Prompt is not appearing over the Company Portal.
The Application Deployment Setting "Show All Notifications" is configured for the Assignment.
I also tested the Application through a User Deployment (Available) and Device Deployment (Required), this didnt work as well.
        
This is my PSADT Line:
## Show Installation Welcome + Close Apps
Show-InstallationWelcome -CloseApps 'msrdcw=Remote Desktop' -BlockExecution -PersistPrompt -AllowDefer -DeferTimes 3

The Log is showing me the following Line.
[Pre-Installation] :: Bypassing Function [Block-AppExecution], because [Mode: NonInteractive].
![Show-Prompt-Log](https://user-images.githubusercontent.com/61466187/162950742-239466d3-0cb2-4135-9483-5f9a5d424037.png)

This Message confused me, so I tried to give the Paramters over the Installation call, unfortunately this didnt help either.
![Install_Call](https://user-images.githubusercontent.com/61466187/162951174-d0e23c36-43c8-42ed-943b-18e13df67fb7.png)

I tried this procedure with the PSAPDT Version 3.8.4, 3.8.3 and 3.7.1.

Could anyone help me out, or knows where my issue could be?
Thanks for the help in advance.

Greetings

Iboo ;)

**Comment by powershellking** [comment]
Hey Iboo,

I was struggling with the exact same thing about one year ago. The thing is that Intune is not made for user interaction in application installations. To make this possible I needed to use the ServiceUI64.exe from MDT to call PSADT. It's very important to use the 64-bit version because the Intune Management Extensions invokes app installations in a 32 bit context. So you need to copy ServiceUI64.exe to your PSADT root folder. If you used to call Deploy-Application.ps1 directly now it's required to use Deploy-Applcation.exe and Deploy-Application.ps1. It's important that Deploy-Application.ps1 is not renamed because Deploy-Application.exe has a hard coded reference to Deploy-Application.ps1. So also copy Deploy-Application.exe and Deploy-Application.ps1 to your PSADT root folder. And finally your command line for installation commandline should look like:

`ServiceUI_64.exe -Process:explorer.exe Deploy-Application.exe <Parameters to pass to Deploy-Application.ps1>`

Greetings
powershellking
