### ISSUE TITLE
Registry entries that block some applications during the installation are not cleaned up at the next startup after the installation script has frozen or been interrupted.

### ISSUE THREAD

**Issue by denisrennesOR** [PSAppDeployToolkit/PSAppDeployToolkit#714]
**Describe the bug**
Registry entries that block some applications during the installation are not cleaned up at the next startup after the installation script has frozen or been interrupted.

**To Reproduce**
Use "Show-InstallationWelcome -CloseApps 'notepad' ...." and add an "exit" line right after, to simulate an installation that has frozen or been interrupted.
Restart the PC.
Try to run Notepad.exe: the usual message is displayed, preventing to run notepad.exe.

Cause:
The scheduled task "..._BlockedApps" returns an error 0xFFFD0000 and does not delete blocking registry entries nor does it self-destruct.
This is because the command line syntax is now incorrect, surrounding arguments with simple quotes instead of double quotes: this command launches Powershell but this command is not run by Powershell, it is run by the Windows Task Scheduler, so it must use double quotes to surround arguments.

**Screenshots**
![image](https://user-images.githubusercontent.com/106231225/170232543-4bf596ce-3d4f-4b9c-a8fb-dbf5aa4393d8.png)

**Toolkit Version:**
3.8.4

**Powershell Version:**
5.1

**Comment by denisrennesOR** [comment]
I submetted the Pull request #715 to fix this.

**Comment by denisrennes** [comment]
Any deployment based on the toolkit version 3.8.4 since Tue Feb 9 2021 (commit 68d1c477e058ea5ca2a402949bfb85e50b25be95) has this bug: 
If the -BlockExecution parameter is specified with the Show-InstallationWelcome function to block applications while the installation is in progress and if the installation freezes or is interrupted, these applications will remain blocked forever. Even after a reboot a message will be displayed to the user to indicate that execution of the application has been blocked while the installation is in progress.
I faced this problem a few times for MS 365 package and Adobe Acrobat Reader DC package. Sometimes the installers freeze and even if the application is installed, the user cannot execute it, even after a reboot. This is a rare case but is very difficult to fix.

That is because the scheduled task supposed to unblock the applications at the next system startup dos not work anymore: the command scheduled to be executed at the system startup has a syntax error, using simple quotes instead of double quotes.
The author of this bug thought that the command was a command executed by Powershell and therefore replaced the double quotes with single quotes. This was a mistake because this command launches a Powershell script, but it is executed by Windows and must use double quotes. With this bug the unblocking command is not launched, there is an error returned to the Task Scheduler. The registry entries blocking the application are not deleted, the application are blocked forever.
