### ISSUE TITLE
Execute-MSI and SkipMSIAlreadyInstalledCheck Switch not working correct?

### ISSUE THREAD

**Issue by Malte-Sc** [PSAppDeployToolkit/PSAppDeployToolkit#716]
Hello, 
I have an MSI thats beeing not recognized as installed by the Execute-MSI Function, because the product code in the MSI Properties differs from the Registry Value. So I tried using the Execute-MSI -Action Repair Function with the SkipMSIAlreadyInstalledCheck switch. 
Unfortunately the SkipMSIAlreadyInstalledCheck Switch seems not to work in combination with the Repair Action.
After looking through the Code I might thing the issue is at this line:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/46c98f1caa99b1640fd890b6e76ce0409ac12724/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L2680

Not sure about the logic behind the whole thing, but shouldn't that be [boolean]$IsMsiInstalled = $true instead of $false?

Toolkit Version:
3.8.4

Powershell Version:
5.1

**Comment by That-Annoying-Guy** [comment]
Check your MSI logs. I'm guessing you are installing something that is equivalent to something that is already installed. Different MSI `PRODUCTGUID `but the MSI itself is determining that your MSI is not needed. PSADT would not be able to workaround this issue without some direction.

**Comment by hung3r** [comment]
I run through the Execute-MSI Function with the debugger: There is no MSI Log, because the function is not executing msiexec due to the missing detection:
`
[05-31-2022 22:06:45.804] [Initialization] [PSAppDeployToolkit] :: Deployment type is [Installation].
[05-31-2022 22:06:45.858] [Installation] [Get-MsiTableProperty] :: Read data from Windows Installer database file [C:\_Packaging\9.1.11723.1\Files\PulseSecure.x64.msi] in table [Property].
[05-31-2022 22:06:46.145] [Installation] [Execute-MSI] :: The MSI is not installed on this system. Skipping action [Repair]...
[05-31-2022 22:06:46.168] [Installation] [Close-InstallationProgress] :: Bypassing Close-InstallationProgress [Mode: nonInteractive]
[05-31-2022 22:06:46.185] [Installation] [Exit-Script] :: PulseSecure_PulseSecure_9.1.11723.1_MUI_0 Installation completed with exit code [0].
[05-31-2022 22:06:46.195] [Installation] [Exit-Script] :: -------------------------------------------------------------------------------
`

The problem is, that the PulseSecure.x64.msi MSIGUID cannot be found with the Get-InstalledApplication Function.

**Comment by neo42mgn** [comment]
If you don't want to check for the installed msi and want to run it anyways, you have no chance but to call msiexec directly without utilizing the PSADT function here, this does not seam right.
The Code within Execute-MSI should be like this as already mentioned in the first post I think, just change $false to $true here:
`If ($MSIProductCode) {`
`            If ($SkipMSIAlreadyInstalledCheck) {`
 **[Boolean]$IsMsiInstalled = $true**
`            }`
`            Else {`
`                If ($IncludeUpdatesAndHotfixes) {`
`                    [PSObject]$MsiInstalled = Get-InstalledApplication -ProductCode $MSIProductCode -IncludeUpdatesAndHotfixes`
`                }`
`                Else {`
`                    [PSObject]$MsiInstalled = Get-InstalledApplication -ProductCode $MSIProductCode`
`                }`
`                If ($MsiInstalled) {`
`                    [Boolean]$IsMsiInstalled = $true`
`                }`
`            }`
`        }`

**Comment by mjr4077au** [comment]
`Start-ADTMsiProcess` (previously `Execute-MSI`) has undergone significant rewrites for v4. If this is still a problem, please raise a new issue against v4.
