### ISSUE TITLE
Add option to suppressing logging the value of non-default parameters

### ISSUE THREAD

**Issue by sjfairchild** [PSAppDeployToolkit/PSAppDeployToolkit#731]
I have a script that requires a password to perform tasks. For obvious reasons I'm not storing the password in the file. In Deploy-Application.ps1 I added the following parameter to accept the password from the command line

[Parameter(Mandatory=$true)]
[string]$pw

I run the script by using: Deploy-Application.exe -pw "P@ssw0rd"

The problem is PSADT logs the password

[Initialization] :: The following non-default parameters were passed to [Deploy Application]: [-pw "P@ssw0rd"]

Can you add an option that allows for suppressing the value of non-default parameters. It would be nice to see that a parameter was passed, just not the value for security reasons.

Thanks!

**Comment by mjr4077au** [comment]
This is security via obscurity. Just because the log suppresses it doesn't mean you can't get at it via Process Explorer, etc. In saying this though, in the upcoming v4 preview release, if you remove the `DeployAppScriptParameters = $PSBoundParameters` line from your `Invoke-AppDeployToolkit.ps1` script, it will not log what parameters have been passed.
