### ISSUE TITLE
Execute-ProcessAsUser running when not being used

### ISSUE THREAD

**Issue by LionZum** [PSAppDeployToolkit/PSAppDeployToolkit#782]
**Describe the bug**
I am not doing any calling of execute-process as user but its triggering in pre and post phase.  Policies prevent the running of vbs so it results in a popup warning.

**To Reproduce**
```
[string]$installPhase = 'Pre-Installation'

		## Show Welcome Message, close Internet Explorer if required, allow up to 3 deferrals, verify there is enough disk space to complete the install, and persist the prompt
		Show-InstallationWelcome -CloseApps 'nothing' -AllowDefer -DeferTimes 3 -CheckDiskSpace -PersistPrompt

		## Show Progress Message (with the default message)
		Show-InstallationProgress

		## <Perform Pre-Installation tasks here>
		<#Remove-MSIApplications "Teams Machine-Wide Installer"
		$profiles = Get-UserProfiles
		foreach ($profile in $profiles) {
			if (test-path -Path "$profile\AppData\Local\Microsoft\Teams\"){
				Remove-Folder -Path "$profile\AppData\Local\Microsoft\Teams\"
			}
			[scriptblock]$HKCURegistrySettings = {
				Remove-RegistryKey -Key 'HKCU\Software\Microsoft\Office\Teams' -Name 'PreventInstallationFromMsi' -SID $UserProfile.SID
				}
				Invoke-HKCURegistrySettingsForAllUsers $HKCURegistrySettings
		}
		#>
		[scriptblock]$HKCURegistrySettings = {
			Remove-RegistryKey -Key 'HKCU\Software\Microsoft\Office\Teams' -Name 'PreventInstallationFromMsi' -SID $UserProfile.SID
			}
		#Invoke-HKCURegistrySettingsForAllUsers $HKCURegistrySettings
		$installed = Get-InstalledApplication -Name "Teams Machine-Wide Installer"
		If ($appVersion -gt $installed.ProductVersion){
			Remove-MSIApplications -Name "Teams Machine-Wide Installer"
		}
```

**Screenshots**

**Toolkit Version:**
3.9.2

**Powershell Version:**
5.1

**Additional context**
replace the toolkit files back with 3.8.4 and there are no issues

**Comment by mmashwani** [comment]
Thanks for reporting this. We will move away from using a VBScript for this functionality soon in a new release.

**Comment by ElianeMegert** [comment]
As far as I know the Execute-ProcessAsUser part is launched to show the balloon tip. So even if you dont have any "Execute-ProcessAsUser" in the post-install section it will launch it when not running a silent install or have it turned of in the AppDeployToolkitConfig.xml.

**Comment by apiontek** [comment]
> Thanks for reporting this. We will move away from using a VBScript for this functionality soon in a new release.

If the new approach hasn't already been implemented, I have a reimplementation of this function that I've been using in the extension script to override the original.

My version, if not running as system, uses the task scheduler COM object interface to create the scheduled task. Using that interface you can specify the process should be hidden without needing an intermediary script.

And I say "if not running as system" because I did a whole bit of extra work to utilize native methods in C# code To run a process as the current active user without needing the test scheduler.

So in fact in my extensions PS1 I have:

- Add-Type for my custom RunAs C# code
- Execute-ProcessAsCurrentUser (only works if running as system, has the option to capture output including stderr/stdout)
- Execute-ProcessAsUser (if running in system context, and the username specified matches the one my C# code finds, then it uses Execute-ProcessAsCurrentUser; otherwise it falls back to the task scheduler COM object method)
- Execute-ScriptBlockAsUser (a convenience method for running short script blocks that saves the script as a PS1 and runs it with Execute-ProcessAsUser; can pass string parameters to the script block)

If any of this is of interest should I format it as a full-on pull request or do you want to just take a look at my extension function file & c# addon?

**Comment by sintaxasn** [comment]
@apiontek I dropped you an email.
