### ISSUE TITLE
Bug when exiting the script in Task Sequence deployment.

### ISSUE THREAD

**Issue by LFM8787** [PSAppDeployToolkit/PSAppDeployToolkit#809]
**Describe the bug**
There are some scenarios where the reserved keyword Exit doesn't work as expected.

Today I faced this in an application deployed via Task Sequence. I manually set the script to exit with ExitCode 3010 and the command worked well, the log entry is saved, the function is called but in the smsts.log the exit code returned by the process was always 1.

I remembered then one time while scripting in powershell that I came across with something similar and its solution...

> Do never use Exit and instead use [Environment.Exit(Int32) Method](https://learn.microsoft.com/en-us/dotnet/api/system.environment.exit)

After modifying the following lines using the environment method:

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/216ff9eae560d0cd3e67a02c41b2db2d1e34c416/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L1783
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/216ff9eae560d0cd3e67a02c41b2db2d1e34c416/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L16115
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/216ff9eae560d0cd3e67a02c41b2db2d1e34c416/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L16127
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/216ff9eae560d0cd3e67a02c41b2db2d1e34c416/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L16135
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/216ff9eae560d0cd3e67a02c41b2db2d1e34c416/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L16151
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/216ff9eae560d0cd3e67a02c41b2db2d1e34c416/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L16156
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/216ff9eae560d0cd3e67a02c41b2db2d1e34c416/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L16161

The correct line would be:

```PowerShell
[Environment]::Exit( )
[Environment]::Exit( 0 )
[Environment]::Exit( $exitcode )
[Environment]::Exit( 60005 )
```

**Please, modify the lines that are intended to exit the script and return the exit code with the environment method.**

**To Reproduce**
It's hard to reproduce, it happens sometimes.

**Toolkit Version:**
3.9.3

**Powershell Version:**
5.1

**Additional context**

**Comment by mjr4077au** [comment]
The only time `[System.Environment]::Exit()` is required currently is due to https://github.com/PowerShell/PowerShell/issues/6615, which PowerShell's GitHub bot stupidly closed off, along with a number of other legitimate issues (see https://github.com/PowerShell/PowerShell/issues/21406 for that one)

We likely won't make any such change here as its a bit presumptious to close the entire PowerShell session forcibly on a user, vs `exit` which from a script, only exits the script's scope.

If you've had an exit code of `1`, which is a value we never use, you've likely had an exception somewhere that wasn't caught (i.e. occurred outside a try/catch block) and caused PowerShell to exit out. That means the suggested fix won't fix this at all.
