### ISSUE TITLE
Execute-MSI adding "Transforms" Parameters to uninstall Command Line

### ISSUE THREAD

**Issue by soccerzockt** [PSAppDeployToolkit/PSAppDeployToolkit#828]
**Describe the bug**
When using Execute-Msi -Action Uninstall,  in conjunction with "-SkipMSIAlreadyInstalledCheck $true", the command line created will include TRANSFORMS="true" and TRANSFORMSSECURE="1". This is not supported by msiexec and will break the command / script.
This occurs only when the msi file executed, is currently not installed.
(Needed to force-uninstall remenants of buggy msi installers)

**To Reproduce**
1. Line in deploy-application.ps1:
Execute-MSI -Action Uninstall -Path "MSIFILE.msi" -Parameters "REBOOT=R /qn" -SkipMSIAlreadyInstalledCheck $true -ContinueOnError $true
where MSIFILE.msi is currently not installed on the system executing the script!
		

3. Constructed Commandline includes TRANSFORM Parameters.
4. msiexec return code 1624, which isnt handeld by the script, the script breaks.

**Screenshots**

**Toolkit Version:**
3.9.1

**Powershell Version:**
latest

**Additional context**

**Comment by DanGough** [comment]
Whilst this does indeed sound like a bug, is there a reason why you'd ever want to combine -Action Uninstall and -SkipMSIAlreadyInstalledCheck $true?

You'd only want to uninstall something that is installed, so the 'already installed' check should something you'd normally want to leave in?

**Comment by soccerzockt** [comment]
As mentioned originally, I needed to force-uninstall remenants of buggy msi installers.
Where working with Product Codes ist possible.
Also when scripting with bulks (foreach) of msi files, where some might or might not be installed.

**Comment by DanGough** [comment]
Thanks, this has now been fixed in [this commit](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/52620e05cb17ce83fb3e7700294ce5ff805c0ff0). Bug found on line 3671; this tries to set a [Boolean] as $null if

```ps
[Boolean]$IsMsiInstalled = If ($MSIProductCode) {
    If (!$SkipMSIAlreadyInstalledCheck) {
        If ($IncludeUpdatesAndHotfixes) {
            !!(Get-InstalledApplication -ProductCode $MSIProductCode -IncludeUpdatesAndHotfixes)
        }
        Else {
            !!(Get-InstalledApplication -ProductCode $MSIProductCode)
        }
    }
    # Nothing here to catch return true or false!
}
Else {
    $Action -ne 'Install'
}
```

Replaced with:

```ps
[Boolean]$IsMsiInstalled = If ($MSIProductCode -and -not $SkipMSIAlreadyInstalledCheck) {
    If ($IncludeUpdatesAndHotfixes) {
        !!(Get-InstalledApplication -ProductCode $MSIProductCode -IncludeUpdatesAndHotfixes)
    }
    Else {
        !!(Get-InstalledApplication -ProductCode $MSIProductCode)
    }
}
Else {
    $Action -ne 'Install'
}
```

However, you should still never need to use this combination of parameters - if you're looking to force uninstall remnants of buggy installers, you may be approaching this in the wrong way:

- If supplying an MSI file name, it will grab the product code of that MSI.
- By default it will then check to see if that product code is installed before trying to uninstall.
- The only thing adding -SkipMSIAlreadyInstalledCheck $true -ContinueOnError $true will achieve is trying to uninstall stuff that's not installed, giving you a 1605 error in the log.
