### ISSUE TITLE
Launching Deploy-Application via PSEXEC using ServiceUI with Quoted paths fails.

### ISSUE THREAD

**Issue by Vortex86-R** [PSAppDeployToolkit/PSAppDeployToolkit#835]
We are currently using an Invoke script to launch PSEXEC, using ServiceIU to display Deploy-Application UI to the user as the application is installed.  This all works flawlessly with one exception, that is if $scriptParentPath has a space in it.  To try and resolve the issue I have attempted to add Quotes to the existing command to deal with the spaces.  But this then causes an issue with Deploy-Application.  I have checked the formatting of the various quotes but running another application (with a space in the path) such as notepad++.exe with the same format works as expected.  From testing, the issue doesn’t appear to be the command itself but rather Deploy-Application.exe exiting as the exit code is showing as 0.  It is exiting out the same second that it is launched.  Normally this isn’t an issue as MECM (SCCM) doesn’t have any spaces in its ccmcache paths, but sometimes our technicians will run the package manually on a machine from a path that has a space, I just wanted to head the issue off.

![GitHub_Deploy-Application_Issue_Post_Code_COMPLETE](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/145434711/64c53e75-2606-43a7-b8b2-0df4fd52d54b)

Toolkit Version:3.9.3
PowerShell Version: 5.1

There is an existing open issue which I believe is similar but hasn’t been updated in a while:
[https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/335](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/335)

Thank you

**Comment by Vortex86-R** [comment]
> You must use excape sign for "" within the Parameter Section
> 
> ![image](https://user-images.githubusercontent.com/16757493/268908528-343112de-18a9-4457-9eb5-70561913d942.png)

Hi,
Sorry, it appears my code snippets were not displaying the escape character correctly on github, so I have replaced the text with an image of my command which contains them.

**Comment by cyborgrd** [comment]
idk why you use the ServiceUI_x64.exe within the script. It must be used within the commandline in MECM/SCCM
I use script like here
`

Param (
    [string] $Params = 'Install'
    )

function Starte-Prozess (
  [string]$EXE,
  [string]$Argumente
  ){
    $pinfo = New-Object System.Diagnostics.ProcessStartInfo
    $pinfo.FileName = $EXE
    $pinfo.RedirectStandardError = $true
    $pinfo.RedirectStandardOutput = $true
    $pinfo.UseShellExecute = $false
    $pinfo.Arguments = $Argumente
    $p = New-Object System.Diagnostics.Process
    $p.StartInfo = $pinfo
    $p.Start() | Out-Null
    #Do Other Stuff Here....
    $p.WaitForExit()
    $ExitCode = $p.ExitCode
  
 return $ExitCode
}

$Query = 'Select * from Win32_ComputerSystem Where UserName != NULL'
 
$username = Get-WMIObject -query $Query | Select-Object -Expand UserName
 
IF (($username -ne $null) -and ($username -notlike "*Local_Adm")) 
{
    # a user is logged in  
    $ExitCode = Starte-Prozess 'ServiceUI.exe' "Closeapp-Check-General_1.0_x86.exe $Params"
    exit $ExitCode
    }
Else 
{
    # no user is logged in
    $ExitCode = Starte-Prozess 'Closeapp-Check-General_1.0_x86.exe' "$Params"
    exit $ExitCode
    }

`

**Comment by paulh1541** [comment]
As a colleague of **Adi-R**, I'll give a bit of a background of why we are invoking "psexec with parameters of serviceUI and deploy-application.exe". This does work **100%** fine - just as long as you don't have spaces in your $scriptParentPath (which to be fair isn't typical but is something we noticed)

The reason we don't run ServiceUI directly from SCCM is because we want a **single** package and Deployment Type that can run "whether or not a user is logged on" AND also displays interaction for logged-on users **including RDP session users**.

If we run ServiceUI directly from SCCM's command line this does **not** work for Remote Desktop (RDP) sessions, and we have quite a few of these to consider. The interaction (e.g. dialogue boxes) are not displayed and will timeout, causing negative results.

Our "invoke script" with gather whether or not a user is logged on.
If "no user logged on" we execute-process "Deploy-Application.exe $DeploymentType"
If a user is logged on then we execute-process "psexec > serviceui > deploy-application.exe $DeploymentType"

Although technically only RDP or disconnect-RDP sessions *need* to run PsExec with ServiceUI, by doing this for all user-sessions we are "InTune-Ready" (where ServiceUI will be required for interaction). 

Why are we using PsExec? Without it, we found SCCM deployments would fail. If we manually ran the same line from an administrative PsExec command prompt, it worked fine! So we added PsExec to call ServiceUI and this works 100% and we now have a SINGLE package solution. 

Adi-R has only raised this question because we discovered that IF **$scriptParentPath** has a space in the path then it will fail and this only appears to be only a problem with "Deploy-Application" and works fine with spaces when testing against other apps such as NotePad++.

**Comment by mmashwani** [comment]
Added this as an example to 3.9.4

**Comment by mjr4077au** [comment]
Just my own two cents here, and not sure it's entirely relevant, but I've never had success with ServiceUI launching processes that contain spaces in the path at all. I've got a function that augments `[System.IO.FileInfo]` and `[System.IO.DirectoryInfo]` objects with DOS 8.3 shortnames, which archaic as it is, do work with ServiceUI without issue.

```PowerShell
function Get-ItemWithShortProperties
{
	<#

	.SYNOPSIS
	Returns one or more FileSystemInfo objects appended with DOS short file name (8.3 format) properties.

	.DESCRIPTION
	This function accepts one or more file paths and returns as a FileSystemInfo object appended with DOS short file name (8.3 format) properties.

	.PARAMETER InputObject
	One or more files/directories to retrieve a short name/path for.

	.INPUTS
	System.Object. Get-ItemWithShortProperties accepts one or more file paths, either as DirectoryInfo, FileInfo, or any valid file path that 'Test-Path' can validate.

	.OUTPUTS
	System.IO.FileSystemInfo. Get-ItemWithShortProperties returns one or more FileSystemInfo objects appended with DOS short file name (8.3 format) properties.

	#>

	Param (
		[Parameter(Mandatory = $true, ValueFromPipeline = $true)]
		[ValidateScript({Test-Path -LiteralPath $_})]
		[Alias('LiteralPath')]
		$InputObject
	)

	begin {
		# Create new FileSystem COM object.
		$fso = New-Object -ComObject Scripting.FileSystemObject
	}

	process {
		# Run this through a loop in case the caller has provided multiple values.
		foreach ($Object in $InputObject)
		{
			# If provided path is a string, turn it into a real object.
			if ($Object -isnot [System.IO.FileSystemInfo])
			{
				$Object = Get-Item -LiteralPath $Object
			}

			# Get the short name, handing whether it's a file or folder.
			$fsoObj = if ($Object.PSIsContainer)
			{
				$fso.GetFolder($Object.FullName)
			}
			else
			{
				$fso.GetFile($Object.FullName)
			}

			# Add new properties to the FileSystemInfo object.
			$Object.PSObject.Properties.Add([System.Management.Automation.PSNoteProperty]::new('ShortName', $fsoObj.ShortName))
			$Object.PSObject.Properties.Add([System.Management.Automation.PSNoteProperty]::new('ShortPath', $fsoObj.ShortPath))

			# Clean up the COM object before returning.
			$fsoObj | Clear-ComObject
			$Object
		}
	}

	end {
		# Clean up the COM object before finishing.
		$fso | Clear-ComObject
	}
}
```

**Comment by DanGough** [comment]
This example makes my head spin... Execute-Process is used (which means we're already in PSADT land) to run PsExec (but we should already be running as system) to then call ServiceUI (which we only need to use with Intune) to run PSADT!

Also, PsExec is blocked or tracked in a lot of environments - I have triggered security alerts using it at banks to test deployments 😁. So we should avoid using it if possible.

I'm thankful for the discussion around ServiceUI not liking spaces though - it appears it strips the quotes off of whatever it's fed. I started off following Mitch's example of getting the shortname, but was concerned that Scripting.FileSystemObject might not be available after removing VBScript - turns out that's not an issue btw, but I used a different approach anyhow:

```ps
if (-not ([System.Management.Automation.PSTypeName]'PSADT.FileUtil').Type) {
    Add-Type -TypeDefinition @"
    using System;
    using System.Runtime.InteropServices;
    namespace PSADT {
        public class FileUtil {
            [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
            public static extern uint GetShortPathName(
                string lpszLongPath,
                [Out] System.Text.StringBuilder lpszShortPath,
                uint cchBuffer
            );
        }
    }
"@
}

$ShortPath = New-Object System.Text.StringBuilder 260
[PSADT.FileUtil]::GetShortPathName($PSScriptRoot, $ShortPath, $ShortPath.Capacity) | Out-Null
$ShortPSScriptRoot = $ShortPath.ToString()
```

But then I recalled how many times I've encountered servers that were 'optimised' by disabling 8.3 naming (which causes issues with App-V). So I figured it's a heck of a lot easier just to call `Set-Location $PSScriptRoot` and forget the path issue altogether!

I've created a gist here with the script I came up with - if anyone interested would like to give it a try and has any suggestions, please post them to gist page itself:

https://gist.github.com/DanGough/7ad3b9193ae66c0573fa5986c181c491

**Comment by mjr4077au** [comment]
My only feedback RE: `Set-Location` is for situations like where I'm installing an Intune app, I very much expect the location to be the root of the decompressed intunewin file so wholesale setting the current directory to be something else could lead to unexpected behaviour depending on how someone packages things up, etc. It probably just depends on whether someone's shipping all the files together with their app vs. abstracting them into a dependency app so the script is available as an updatable handler.

I like the C# P/Invoke example for getting the short path name vs. my approach of using FSO. I might shamelessly borrow that for my side 😉

**Comment by Vortex86-R** [comment]
The alternative to PSEXEC that we use is a Task Schedule.  In-fact its our fall back method if the PSEXEC executable doesn't exist for any reason.  I believe we have some pretty unique methods that allow us to deploy via SCCM(Available/Required/Task Sequence)/Intune or Manual Install.  And this is to machines where the user is connected via RDP or logged in normally or not logged on at all(or even in one case Explorer.exe isn't running) all from one PSADT script.

**Comment by DanGough** [comment]
@Vortex86-R I would appreciate if you could check out the script I posted, my hope is that it should stop you ever having to use a scheduled task or psexec at all.

SCCM/Intune already execute your chosen program in system context, and the script invokes ServiceUI to make it visible if explorer (by default) is running - which works over RDP also in my tests.
