### ISSUE TITLE
Cannot convert the "" value of type "System.String" to type "System.Collections.Hashtable".

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#942]
**Describe the bug**

The following error appears when AppDeployToolkitMain.ps1 is loaded from powershell ISE 5.1

`Cannot convert the "" value of type "System.String" to type "System.Collections.Hashtable".`

**Screenshots**
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/15003329/77c09503-85d1-4991-8f71-f85133fe0b11)

**Toolkit Version:**
3.10.0

**Powershell Version:**
5.1

**Additional context**
The error comes from line16824

[Hashtable]$appDeployMainScriptAsyncParameters = $appDeployMainScriptParameters

$appDeployMainScriptAsyncParameters value is empty so it can't be converted to a hashtable variable.

![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/15003329/e1e77851-1baf-44e8-b2da-f48a81e7b6ec)

**Comment by DanGough** [comment]
That doesn’t happen with the standard toolkit in my experience - try uninstalling your module and running it again?

**Comment by DanGough** [comment]
Still, I’d advise unloading/uninstalling the module and seeing if you can repeat the issue by just running the toolkit standalone. From here, it looks like a bug in how the module is loading the toolkit.

**Comment by mjr4077au** [comment]
When we look at the current source code, its not possible for your issue to occur since `$appDeployMainScriptParameters` hasn't been re-written into a string of params/arguments yet: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/d04eda2cf83762604ae567b050dd7dea9d969d20/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L16824-L16827
The problem is the code as it currently stands is not really suited to be a module, yet you've made it a module anyway. You're going to have to ensure that all variables that initialise within the script's scope (in a module, $Script: == module's global scope) are destructed appropriately.
